package Daniela.ComexApp.Frames;

import config.Conexion;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import service.OperacionNacionalParticipantesImpl;
import service.StockImpl;

/**
 *
 * @author Daniela
 */
public class AsociarOperacionNacional extends javax.swing.JFrame {

     String usuario = "", rol = "", nombreCompleto = "";
    /**
     * Creates new form AsociarOperacionInternacional
     */
    public AsociarOperacionNacional() {
        initComponents();
        
        setSize(850, 500);
        setLayout(null);
        setLocationRelativeTo(null);
        setResizable(false);
        
        PaginaPrincipal paginaPrincipal = new PaginaPrincipal();
        
        usuario = paginaPrincipal.usuario;
        nombreCompleto = paginaPrincipal.nombreCompleto;
        
        setTitle("Asociar operación nacional - " + usuario + " - sistema ComexApp");
        
        jPanelStock.setVisible(false);
        jPanelVer.setVisible(true);

        mostrarTodosLasAsociaciones();
    }

    // icono
    public Image getLogo(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/loguito1.png"));
        return retValue;   
    }
    
    StockImpl stockImpl = new StockImpl();
    OperacionNacionalParticipantesImpl participantes = new OperacionNacionalParticipantesImpl();
    
    // conexión
    Conexion cn = new Conexion();
    Connection conec;
    PreparedStatement pst;
    ResultSet rs;

    
    
    public void cargarTablaAsociados(String sql){

        DefaultTableModel modelo = new DefaultTableModel();
      
        try{
            conec = cn.Conexion();
            pst = conec.prepareStatement(sql);
            rs = pst.executeQuery();
            
            jTableAsociaciones = new JTable(modelo);
            jScrollPane1.setViewportView(jTableAsociaciones);
            
            modelo.addColumn("N° operación nacional");
            modelo.addColumn("Comprador");
            modelo.addColumn("Vendedor");
            modelo.addColumn("Producto ID");
            modelo.addColumn("Status");
            modelo.addColumn("Disponible en stock");
            
            while(rs.next()){
                Object[] fila = new Object[6];
                for(int i = 0; i < 6; i++){
                    fila[i] = rs.getObject(i + 1);
                }
               modelo.addRow(fila);
            }
            
            conec.close();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Error al cargar tabla");
            System.err.println("Error al cargar la tabla " + e);
        }
    }

   
     public void mostrarTodosLasAsociaciones(){
         String sql = "select numero_op_nac, comprador, vendedor, id_producto, "
                 + "status, stock_modificado from participantes_opnac_con order "
                 + "by numero_op_nac asc";
        cargarTablaAsociados(sql);
    }
     
     
   
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelVer = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAsociaciones = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButtonVolver = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        textID = new javax.swing.JTextField();
        jButtonStock = new javax.swing.JButton();
        jButtonVer = new javax.swing.JButton();
        jPanelStock = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButtonAsociarStock = new javax.swing.JButton();
        textProducto = new javax.swing.JTextField();
        textCodigoProducto = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        textVendedor = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(getLogo());
        setIconImages(getIconImages());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelVer.setBackground(new java.awt.Color(255, 255, 255));
        jPanelVer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableAsociaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jTableAsociaciones.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTableAsociaciones.setEnabled(false);
        jTableAsociaciones.setSelectionBackground(new java.awt.Color(0, 0, 153));
        jTableAsociaciones.setSelectionForeground(new java.awt.Color(0, 0, 153));
        jTableAsociaciones.setShowHorizontalLines(true);
        jScrollPane1.setViewportView(jTableAsociaciones);

        jPanelVer.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 30, 610, -1));

        getContentPane().add(jPanelVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 640, 500));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 153));
        jPanel2.setForeground(new java.awt.Color(0, 0, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonVolver.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonVolver.setForeground(new java.awt.Color(0, 0, 153));
        jButtonVolver.setText("Volver");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 110, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 153));
        jButton1.setText("ID Operación");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        textID.setForeground(new java.awt.Color(0, 0, 153));
        jPanel2.add(textID, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 70, -1));

        jButtonStock.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonStock.setForeground(new java.awt.Color(0, 0, 153));
        jButtonStock.setText("Stock");
        jButtonStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStockActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 170, 20));

        jButtonVer.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonVer.setForeground(new java.awt.Color(0, 0, 153));
        jButtonVer.setText("Ver asociados");
        jButtonVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 170, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 500));

        jPanelStock.setBackground(new java.awt.Color(255, 255, 255));
        jPanelStock.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setText("Producto:");
        jPanelStock.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        jButtonAsociarStock.setBackground(new java.awt.Color(0, 0, 153));
        jButtonAsociarStock.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonAsociarStock.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAsociarStock.setText("Asociar al stock");
        jButtonAsociarStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAsociarStockActionPerformed(evt);
            }
        });
        jPanelStock.add(jButtonAsociarStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, -1, 25));

        textProducto.setForeground(new java.awt.Color(0, 0, 153));
        jPanelStock.add(textProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 150, -1));

        textCodigoProducto.setForeground(new java.awt.Color(0, 0, 153));
        jPanelStock.add(textCodigoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 150, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 153));
        jLabel9.setText("Código del producto:");
        jPanelStock.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        textVendedor.setForeground(new java.awt.Color(0, 0, 153));
        jPanelStock.add(textVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 150, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 153));
        jLabel10.setText("Vendedor:");
        jPanelStock.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 153));
        jLabel11.setText("Es necesario completar todos estos datos para asociar al producto debido.");
        jPanelStock.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));

        jPanel1.add(jPanelStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 490, 500));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1500, 880));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        
        this.dispose();
        
    }//GEN-LAST:event_jButtonVolverActionPerformed

    private void jButtonStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStockActionPerformed
        
        jPanelStock.setVisible(true);
        jPanelVer.setVisible(false);
        
    }//GEN-LAST:event_jButtonStockActionPerformed

    private void jButtonAsociarStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAsociarStockActionPerformed
        
        String producto, vendedor, codigo;
        int ID;
        
        producto = textProducto.getText().trim();
        vendedor = textVendedor.getText().trim();
        codigo = textCodigoProducto.getText().trim();
        
        ID = Integer.parseInt(textID.getText().trim());
        
        int IDProducto = stockImpl.obtenerIDProducto(codigo, vendedor, producto);
        participantes.agregarIDProducto(IDProducto, ID);
        stockImpl.asociarCantidadesAOperacionNacional(producto, vendedor, codigo, ID);
        
    }//GEN-LAST:event_jButtonAsociarStockActionPerformed

    private void jButtonVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerActionPerformed
        
        jPanelStock.setVisible(false);
        jPanelVer.setVisible(true);
        
    }//GEN-LAST:event_jButtonVerActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AsociarOperacionNacional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AsociarOperacionNacional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AsociarOperacionNacional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AsociarOperacionNacional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AsociarOperacionNacional().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAsociarStock;
    private javax.swing.JButton jButtonStock;
    private javax.swing.JButton jButtonVer;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelStock;
    private javax.swing.JPanel jPanelVer;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAsociaciones;
    private javax.swing.JTextField textCodigoProducto;
    private javax.swing.JTextField textID;
    private javax.swing.JTextField textProducto;
    private javax.swing.JTextField textVendedor;
    // End of variables declaration//GEN-END:variables
}
