package Daniela.ComexApp.Frames;

import java.awt.Image;
import java.awt.Toolkit;
import service.ContenedoresImpl;
import service.DespachantesImpl;
import service.ExportadoresImpl;
import service.ImportadoresImpl;
import service.OperacionInternacionalParticipantesImpl;
import service.StockImpl;

/**
 *
 * @author Daniela
 */
public class AsociarOperacionInternacional extends javax.swing.JFrame {

     String usuario = "", rol = "", nombreCompleto = "";
    /**
     * Creates new form AsociarOperacionInternacional
     */
    public AsociarOperacionInternacional() {
        initComponents();
        
        setSize(700, 500);
        setLayout(null);
        setLocationRelativeTo(null);
        setResizable(false);
        
        PaginaPrincipal paginaPrincipal = new PaginaPrincipal();
        
        usuario = paginaPrincipal.usuario;
        nombreCompleto = paginaPrincipal.nombreCompleto;
        
        setTitle("Asociar operación internacional - " + usuario + " - sistema ComexApp");
        
        jPanelContenedor.setVisible(true);
        
    }

    // icono
    public Image getLogo(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/loguito1.png"));
        return retValue;   
    }
    
    ContenedoresImpl contenedoresImpl = new ContenedoresImpl();
    StockImpl stockImpl = new StockImpl();
    DespachantesImpl despachantesImpl = new DespachantesImpl();
    ExportadoresImpl exportadoresImpl = new ExportadoresImpl();
    ImportadoresImpl importadoresImpl = new ImportadoresImpl();
    OperacionInternacionalParticipantesImpl participantes = new OperacionInternacionalParticipantesImpl();
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButtonVolver = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        textID = new javax.swing.JTextField();
        jButtonContenedor = new javax.swing.JButton();
        jButtonStock = new javax.swing.JButton();
        jButtonParticipante = new javax.swing.JButton();
        jButtonTransporte = new javax.swing.JButton();
        jPanelContenedor = new javax.swing.JPanel();
        jButtonAsociarCont = new javax.swing.JButton();
        textCodigo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanelStock = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButtonAsociarStock = new javax.swing.JButton();
        textProducto = new javax.swing.JTextField();
        textCodigoProducto = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        textVendedor = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanelParticipante = new javax.swing.JPanel();
        textExportador = new javax.swing.JTextField();
        jButtonAsociarExp = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButtonAsociarImp = new javax.swing.JButton();
        textImportador = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButtonAsociarDesp = new javax.swing.JButton();
        textEmpresaDes = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        textDespachante = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        textEmpresaIm = new javax.swing.JTextField();
        textEmpresaEx = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jPanelTransporte = new javax.swing.JPanel();
        textProducto2 = new javax.swing.JTextField();
        jButtonAsociarStock2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getLogo());
        setIconImages(getIconImages());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 153));
        jPanel2.setForeground(new java.awt.Color(0, 0, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonVolver.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonVolver.setForeground(new java.awt.Color(0, 0, 153));
        jButtonVolver.setText("Volver");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 110, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 153));
        jButton1.setText("ID Operación");
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        textID.setForeground(new java.awt.Color(0, 0, 153));
        jPanel2.add(textID, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 70, -1));

        jButtonContenedor.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonContenedor.setForeground(new java.awt.Color(0, 0, 153));
        jButtonContenedor.setText("Contenedor");
        jButtonContenedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonContenedorActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonContenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 170, 20));

        jButtonStock.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonStock.setForeground(new java.awt.Color(0, 0, 153));
        jButtonStock.setText("Stock");
        jButtonStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStockActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 170, 20));

        jButtonParticipante.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonParticipante.setForeground(new java.awt.Color(0, 0, 153));
        jButtonParticipante.setText("Participante");
        jButtonParticipante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonParticipanteActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonParticipante, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 170, 20));

        jButtonTransporte.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonTransporte.setForeground(new java.awt.Color(0, 0, 153));
        jButtonTransporte.setText("Transporte");
        jButtonTransporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTransporteActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonTransporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 170, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 500));

        jPanelContenedor.setBackground(new java.awt.Color(255, 255, 255));
        jPanelContenedor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonAsociarCont.setBackground(new java.awt.Color(0, 0, 153));
        jButtonAsociarCont.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonAsociarCont.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAsociarCont.setText("Asociar al contenedor");
        jButtonAsociarCont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAsociarContActionPerformed(evt);
            }
        });
        jPanelContenedor.add(jButtonAsociarCont, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, -1, 25));

        textCodigo.setForeground(new java.awt.Color(0, 0, 153));
        jPanelContenedor.add(textCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 140, 150, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Código de contenedor:");
        jPanelContenedor.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        jPanel1.add(jPanelContenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 490, 500));

        jPanelStock.setBackground(new java.awt.Color(255, 255, 255));
        jPanelStock.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setText("Producto:");
        jPanelStock.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        jButtonAsociarStock.setBackground(new java.awt.Color(0, 0, 153));
        jButtonAsociarStock.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonAsociarStock.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAsociarStock.setText("Asociar al stock");
        jButtonAsociarStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAsociarStockActionPerformed(evt);
            }
        });
        jPanelStock.add(jButtonAsociarStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, -1, 25));

        textProducto.setForeground(new java.awt.Color(0, 0, 153));
        jPanelStock.add(textProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 150, -1));

        textCodigoProducto.setForeground(new java.awt.Color(0, 0, 153));
        jPanelStock.add(textCodigoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 150, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 153));
        jLabel9.setText("Código del producto:");
        jPanelStock.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        textVendedor.setForeground(new java.awt.Color(0, 0, 153));
        jPanelStock.add(textVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 150, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 153));
        jLabel10.setText("Vendedor:");
        jPanelStock.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 153));
        jLabel11.setText("Es necesario completar todos estos datos para asociar al producto debido.");
        jPanelStock.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));

        jPanel1.add(jPanelStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 490, 500));

        jPanelParticipante.setBackground(new java.awt.Color(255, 255, 255));
        jPanelParticipante.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textExportador.setForeground(new java.awt.Color(0, 0, 153));
        jPanelParticipante.add(textExportador, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 150, -1));

        jButtonAsociarExp.setBackground(new java.awt.Color(0, 0, 153));
        jButtonAsociarExp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonAsociarExp.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAsociarExp.setText("Asociar al exportador");
        jButtonAsociarExp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAsociarExpActionPerformed(evt);
            }
        });
        jPanelParticipante.add(jButtonAsociarExp, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 190, 25));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 153));
        jLabel3.setText("Exportador:");
        jPanelParticipante.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        jButtonAsociarImp.setBackground(new java.awt.Color(0, 0, 153));
        jButtonAsociarImp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonAsociarImp.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAsociarImp.setText("Asociar al importador");
        jButtonAsociarImp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAsociarImpActionPerformed(evt);
            }
        });
        jPanelParticipante.add(jButtonAsociarImp, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 190, 25));

        textImportador.setForeground(new java.awt.Color(0, 0, 153));
        jPanelParticipante.add(textImportador, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 150, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 153));
        jLabel5.setText("Importador:");
        jPanelParticipante.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        jButtonAsociarDesp.setBackground(new java.awt.Color(0, 0, 153));
        jButtonAsociarDesp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonAsociarDesp.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAsociarDesp.setText("Asociar al despachante");
        jButtonAsociarDesp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAsociarDespActionPerformed(evt);
            }
        });
        jPanelParticipante.add(jButtonAsociarDesp, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, -1, 25));

        textEmpresaDes.setForeground(new java.awt.Color(0, 0, 153));
        jPanelParticipante.add(textEmpresaDes, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 150, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 153));
        jLabel6.setText("Empresa despachante:");
        jPanelParticipante.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 153));
        jLabel7.setText("Por favor, elige un participante ");
        jPanelParticipante.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 153));
        jLabel8.setText("de la operación internacional");
        jPanelParticipante.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 153));
        jLabel12.setText("Despachante:");
        jPanelParticipante.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, -1));

        textDespachante.setForeground(new java.awt.Color(0, 0, 153));
        jPanelParticipante.add(textDespachante, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 150, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 153));
        jLabel13.setText("Empresa importador:");
        jPanelParticipante.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        textEmpresaIm.setForeground(new java.awt.Color(0, 0, 153));
        jPanelParticipante.add(textEmpresaIm, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 150, -1));

        textEmpresaEx.setForeground(new java.awt.Color(0, 0, 153));
        jPanelParticipante.add(textEmpresaEx, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 150, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 153));
        jLabel14.setText("Empresa exportador:");
        jPanelParticipante.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        jPanel1.add(jPanelParticipante, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 490, 500));

        jPanelTransporte.setBackground(new java.awt.Color(255, 255, 255));
        jPanelTransporte.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textProducto2.setForeground(new java.awt.Color(0, 0, 153));
        jPanelTransporte.add(textProducto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 140, 150, -1));

        jButtonAsociarStock2.setBackground(new java.awt.Color(0, 0, 153));
        jButtonAsociarStock2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonAsociarStock2.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAsociarStock2.setText("Asociar al stock");
        jPanelTransporte.add(jButtonAsociarStock2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, -1, 25));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 153));
        jLabel4.setText("Producto:");
        jPanelTransporte.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        jPanel1.add(jPanelTransporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 490, 500));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1500, 880));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonVolverActionPerformed

    private void jButtonContenedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonContenedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonContenedorActionPerformed

    private void jButtonStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonStockActionPerformed

    private void jButtonParticipanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonParticipanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonParticipanteActionPerformed

    private void jButtonTransporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTransporteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonTransporteActionPerformed

    private void jButtonAsociarStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAsociarStockActionPerformed
        
        String producto, vendedor, codigo;
        
        producto = textProducto.getText().trim();
        vendedor = textVendedor.getText().trim();
        codigo = textCodigoProducto.getText().trim();
        
        int IDProducto = stockImpl.obtenerIDProducto(codigo, vendedor, producto);
        participantes.agregarIDProducto(IDProducto);
        
    }//GEN-LAST:event_jButtonAsociarStockActionPerformed

    private void jButtonAsociarContActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAsociarContActionPerformed
        
        String codigo = textCodigo.getText().trim();
        
        int IDContenedor = contenedoresImpl.obtenerIDConCodigoDelContenedor(codigo);
        participantes.agregarIDContenedor(IDContenedor);
        
    }//GEN-LAST:event_jButtonAsociarContActionPerformed

    private void jButtonAsociarDespActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAsociarDespActionPerformed
        
        String empresaDes, despachante;
        
        empresaDes = textEmpresaDes.getText().trim();
        despachante = textDespachante.getText().trim();
        
        int IDDespachante = despachantesImpl.obtenerIDDespachante(empresaDes, empresaDes);
        participantes.agregarIDDespachante(IDDespachante);
        
    }//GEN-LAST:event_jButtonAsociarDespActionPerformed

    private void jButtonAsociarExpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAsociarExpActionPerformed
       
        String empresaEx, exportador;
        
        empresaEx = textEmpresaEx.getText().trim();
        exportador = textExportador.getText().trim();
        
        int IDExportador = exportadoresImpl.obtenerIDExportador(empresaEx, empresaEx);
        participantes.agregarIDExportador(IDExportador);
        
    }//GEN-LAST:event_jButtonAsociarExpActionPerformed

    private void jButtonAsociarImpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAsociarImpActionPerformed
        
        String empresaImp, importador;
        
        empresaImp = textEmpresaIm.getText().trim();
        importador = textImportador.getText().trim();
        
        int IDImportador = importadoresImpl.obtenerIDImportador(empresaImp, importador);
        participantes.agregarIDImportador(IDImportador);
        
    }//GEN-LAST:event_jButtonAsociarImpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AsociarOperacionInternacional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AsociarOperacionInternacional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AsociarOperacionInternacional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AsociarOperacionInternacional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AsociarOperacionInternacional().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAsociarCont;
    private javax.swing.JButton jButtonAsociarDesp;
    private javax.swing.JButton jButtonAsociarExp;
    private javax.swing.JButton jButtonAsociarImp;
    private javax.swing.JButton jButtonAsociarStock;
    private javax.swing.JButton jButtonAsociarStock2;
    private javax.swing.JButton jButtonContenedor;
    private javax.swing.JButton jButtonParticipante;
    private javax.swing.JButton jButtonStock;
    private javax.swing.JButton jButtonTransporte;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelContenedor;
    private javax.swing.JPanel jPanelParticipante;
    private javax.swing.JPanel jPanelStock;
    private javax.swing.JPanel jPanelTransporte;
    private javax.swing.JTextField textCodigo;
    private javax.swing.JTextField textCodigoProducto;
    private javax.swing.JTextField textDespachante;
    private javax.swing.JTextField textEmpresaDes;
    private javax.swing.JTextField textEmpresaEx;
    private javax.swing.JTextField textEmpresaIm;
    private javax.swing.JTextField textExportador;
    private javax.swing.JTextField textID;
    private javax.swing.JTextField textImportador;
    private javax.swing.JTextField textProducto;
    private javax.swing.JTextField textProducto2;
    private javax.swing.JTextField textVendedor;
    // End of variables declaration//GEN-END:variables
}
