package Daniela.ComexApp.Frames;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import service.AereoImpl;
import service.AgendaPersonalImpl;
import service.DespachantesImpl;
import service.ExportadoresImpl;
import service.ImportadoresImpl;
import service.MaritimasImpl;

/**
 *
 * @author Daniela
 */
public class BuscarMail extends javax.swing.JFrame{

     String usuario = "", nombreCompleto = "", contraseña = "";
    /**
     * Creates new form BuscarMail
     */
    public BuscarMail() {
        initComponents();
        
        setSize(380, 230);
        setLayout(null);
        setLocationRelativeTo(null);
        setResizable(false);
        
        PaginaPrincipal paginaPrincipal = new PaginaPrincipal();
        
        usuario = paginaPrincipal.usuario;
        nombreCompleto = paginaPrincipal.nombreCompleto;
        contraseña = paginaPrincipal.contraseña;
        
        setTitle("Obtención de mail " + usuario + " - sistema ComexApp");
    }
    // icono
    public Image getLogo(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/loguito1.png"));
        return retValue;   
    }

    AereoImpl aereo = new AereoImpl();
    AgendaPersonalImpl agenda = new AgendaPersonalImpl();
    DespachantesImpl despachantes = new DespachantesImpl();
    ImportadoresImpl impo = new ImportadoresImpl();
    ExportadoresImpl expo = new ExportadoresImpl();
    MaritimasImpl maritimas = new MaritimasImpl();
    
    
    public void LimpiarCampos(){
        textNombre.setText("");
    }
   
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelContraseña = new javax.swing.JLabel();
        jButtonBuscar = new javax.swing.JButton();
        cmbArea = new javax.swing.JComboBox<>();
        jLabelContraseña1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        textNombre = new javax.swing.JTextField();
        textMail = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(getLogo());
        setIconImages(getIconImages());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(0, 0, 153));
        jLabelTitulo.setText("Obtener mail");
        jPanel1.add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 160, 50));

        jLabelContraseña.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelContraseña.setForeground(new java.awt.Color(0, 0, 153));
        jLabelContraseña.setText("Nombre empleado:");
        jPanel1.add(jLabelContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 140, -1));

        jButtonBuscar.setBackground(new java.awt.Color(0, 0, 153));
        jButtonBuscar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonBuscar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBuscar.setText("Buscar");
        jButtonBuscar.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, -1, 20));

        cmbArea.setForeground(new java.awt.Color(0, 0, 153));
        cmbArea.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Importador", "Exportador", "Despachante", "Marítima", "Aéreo", "Agenda personal" }));
        jPanel1.add(cmbArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 150, -1));

        jLabelContraseña1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelContraseña1.setForeground(new java.awt.Color(0, 0, 153));
        jLabelContraseña1.setText("Área correspondiente:");
        jPanel1.add(jLabelContraseña1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 160, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mail2.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 50, 40));

        textNombre.setBackground(new java.awt.Color(0, 0, 153));
        textNombre.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(textNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 130, -1));

        textMail.setBackground(new java.awt.Color(0, 0, 153));
        textMail.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(textMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 160, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        
        String nombre, mail;
        int areaNivel;
        
        nombre = textNombre.getText().trim();
        areaNivel = cmbArea.getSelectedIndex() + 1;
        
        switch(areaNivel){
            case 1: 
                mail = impo.obtenerMailDelImportador(nombre);
                JOptionPane.showMessageDialog(null, mail);
                textMail.setText(mail);
                break;
            case 2: 
                mail = expo.obtenerMailDelExportador(nombre);
                JOptionPane.showMessageDialog(null, mail);
                textMail.setText(mail);
                break;
            case 3: 
                mail = despachantes.obtenerMailDelDespachante(nombre);
                JOptionPane.showMessageDialog(null, mail);
                textMail.setText(mail);
                break;   
            case 4: 
                mail = maritimas.obtenerMailDeLaMaritima(nombre);
                JOptionPane.showMessageDialog(null, mail);
                textMail.setText(mail);
                break;
            case 5: 
                mail = aereo.obtenerMailDeAereo(nombre);
                JOptionPane.showMessageDialog(null, mail);
                textMail.setText(mail);
                break;
            case 6: 
                mail = agenda.obtenerMailDelContactoPersonal(nombre);
                JOptionPane.showMessageDialog(null, mail);
                textMail.setText(mail);
                break;    
        }
        
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarMail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarMail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarMail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarMail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscarMail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbArea;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelContraseña;
    private javax.swing.JLabel jLabelContraseña1;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField textMail;
    private javax.swing.JTextField textNombre;
    // End of variables declaration//GEN-END:variables
}
