package Daniela.ComexApp.Frames;

import java.awt.Image;
import java.awt.Toolkit;
import service.InicioSesionImp;
import service.MailImpl;
import service.UsuariosImpl;


/**
 *
 * @author Daniela
 */
public class CambioContraseña extends javax.swing.JFrame {

     String usuario = "", nombreCompleto = "", contraseña = "";
    /**
     * Creates new form CambioContraseña
     */
    public CambioContraseña() {
        initComponents();
        
        setSize(460, 400);
        setLayout(null);
        setLocationRelativeTo(null);
        setResizable(false);
        
        PaginaPrincipal paginaPrincipal = new PaginaPrincipal();
        
        usuario = paginaPrincipal.usuario;
        nombreCompleto = paginaPrincipal.nombreCompleto;
        contraseña = paginaPrincipal.contraseña;
        
        setTitle("Cambio de contraseña de " + usuario + " - sistema ComexApp");
    }
    // icono
    public Image getLogo(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/loguito1.png"));
        return retValue;   
    }
    
    InicioSesionImp inicioSesionService = new InicioSesionImp();
    UsuariosImpl usuariosImpl = new UsuariosImpl();
    MailImpl mailImpl = new MailImpl();
    
    
    public void LimpiarCampos(){
        textContraseña.setText("");
        textConfirmacion.setText("");
    }
   
    public void envioDeMailAUsuario(String usuario, String contraseña){
        String mail, contraseñaM, mailApp, asunto, mensaje;
        contraseñaM = "fahbuzfhzpsqnyqm";
        mailApp = "comexappj@gmail.com";
        
        mail = usuariosImpl.obtenerMailUsuario(usuario);
        
  
        asunto = "Cambio de contraseña de usuario";
        mensaje = usuario + " hemos detectado tu cambio de contraseña en el sistema "
                + "ComexApp y es por eso que queremos enviarte un mail notificandote "
                + "tu nueva contraseña para que no la olvides: " + contraseña + 
                ".\n\nPor otro lado, si no has sido tú el que la modificó, te "
                + "recomendamos que entres al sistema y solicites el cambio de tu "
                + "contraseña para evitar que terceros puedan ingresar y operar por "
                + "ti generando conflictos en las operaciones de la empresa y "
                + "perjudicando el trabajo realizado durante todo este tiempo juntos. \n\n"
                + "Muchas gracias por trabajar con nosotros,\n\n           equipo de ComexApp";
        
        mailImpl.envioDeMensajes(mailApp, mail, asunto, mensaje, contraseña);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonCambiar = new javax.swing.JButton();
        jButtonAtras = new javax.swing.JButton();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelContraseña = new javax.swing.JLabel();
        textContraseña = new javax.swing.JPasswordField();
        jLabelConfirmacion = new javax.swing.JLabel();
        textConfirmacion = new javax.swing.JPasswordField();
        jLabelContraseña1 = new javax.swing.JLabel();
        textContraseñaNueva = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(getLogo());
        setIconImages(getIconImages());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonCambiar.setBackground(new java.awt.Color(0, 0, 153));
        jButtonCambiar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonCambiar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCambiar.setText("Realizar cambio de contraseña");
        jButtonCambiar.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jButtonCambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCambiarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCambiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, -1, -1));

        jButtonAtras.setBackground(new java.awt.Color(0, 0, 153));
        jButtonAtras.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonAtras.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAtras.setText("Volver atrás");
        jButtonAtras.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jButtonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtrasActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, -1, -1));

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(0, 0, 153));
        jLabelTitulo.setText("Cambio de contraseña");
        jPanel1.add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 250, 50));

        jLabelContraseña.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelContraseña.setForeground(new java.awt.Color(0, 0, 153));
        jLabelContraseña.setText("Contraseña anterior:");
        jPanel1.add(jLabelContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 160, 30));

        textContraseña.setBackground(new java.awt.Color(0, 0, 153));
        textContraseña.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textContraseña.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(textContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 140, 30));

        jLabelConfirmacion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelConfirmacion.setForeground(new java.awt.Color(0, 0, 153));
        jLabelConfirmacion.setText("Confirmar contraseña:");
        jPanel1.add(jLabelConfirmacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 160, 30));

        textConfirmacion.setBackground(new java.awt.Color(0, 0, 153));
        textConfirmacion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textConfirmacion.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(textConfirmacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 150, 30));

        jLabelContraseña1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelContraseña1.setForeground(new java.awt.Color(0, 0, 153));
        jLabelContraseña1.setText("Contraseña nueva:");
        jPanel1.add(jLabelContraseña1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 160, 30));

        textContraseñaNueva.setBackground(new java.awt.Color(0, 0, 153));
        textContraseñaNueva.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textContraseñaNueva.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(textContraseñaNueva, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 150, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCambiarActionPerformed

        String contraseñaAnterior, contraseñaNueva, confirmacion;
        
        contraseñaAnterior = textContraseña.getText().trim();
        contraseñaNueva = textContraseñaNueva.getText().trim();
        confirmacion = textConfirmacion.getText().trim();
        
        inicioSesionService.cambioContraseña(contraseñaAnterior, contraseñaNueva, 
                confirmacion, usuario);
        envioDeMailAUsuario(usuario, contraseña);
        LimpiarCampos();

    }//GEN-LAST:event_jButtonCambiarActionPerformed

    private void jButtonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtrasActionPerformed
        
        PaginaPrincipal paginaPrincipal = new PaginaPrincipal();
        paginaPrincipal.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButtonAtrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CambioContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CambioContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CambioContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CambioContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CambioContraseña().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtras;
    private javax.swing.JButton jButtonCambiar;
    private javax.swing.JLabel jLabelConfirmacion;
    private javax.swing.JLabel jLabelContraseña;
    private javax.swing.JLabel jLabelContraseña1;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField textConfirmacion;
    private javax.swing.JPasswordField textContraseña;
    private javax.swing.JPasswordField textContraseñaNueva;
    // End of variables declaration//GEN-END:variables
}
