package Daniela.ComexApp.Frames;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileNotFoundException;
import java.sql.Date;
import java.time.LocalDate;
import java.util.Scanner;
import javax.swing.JOptionPane;
import service.PDFContactosImpl;
import service.PDFOperacionesImpl;
import service.PDFProduccionImpl;
import service.ReportesEstadisticasExportacionesImpl;
import service.ReportesEstadisticasGeneralesImpl;

/**
 *
 * @author Daniela
 */
public class CargarDocumento extends javax.swing.JFrame {

     String usuario = "", rol = "", nombreCompleto = "";
    /**
     * Creates new form CargarDocumento
     */
    public CargarDocumento() {
        initComponents();
        
        setSize(700, 500);
        setLayout(null);
        setLocationRelativeTo(null);
        setResizable(false);
        
        PaginaPrincipal paginaPrincipal = new PaginaPrincipal();
        
        usuario = paginaPrincipal.usuario;
        nombreCompleto = paginaPrincipal.nombreCompleto;
      
        setTitle("Cargar documento - " + usuario + " - sistema ComexApp");    
        
            Scanner entrada = null;
        try {
 
            File ruta = jFileChooser.getSelectedFile();
            entrada = new Scanner(ruta);
           
            while(entrada.hasNext()){
                System.out.println(entrada.nextLine());
            }
            
            if(jFileChooser.accept(ruta)){
                
            }
            
        } catch (FileNotFoundException e) {
            System.err.println(e.getMessage());
        } catch (NullPointerException e) {
            System.err.println("No se eligio ningun archivo");
        } catch (Exception e) {
            System.err.println(e.getMessage());
        } finally {
            if(entrada != null){
                entrada.close();
            }
        }
        
    }

    // icono
    public Image getLogo(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/loguito1.png"));
        return retValue;   
    }
    
  
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonVolver2 = new javax.swing.JButton();
        jFileChooser = new javax.swing.JFileChooser();
        jButtonSubir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getLogo());
        setIconImages(getIconImages());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonVolver2.setBackground(new java.awt.Color(0, 0, 153));
        jButtonVolver2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonVolver2.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVolver2.setText("Volver");
        jButtonVolver2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolver2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonVolver2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 380, 94, -1));

        jFileChooser.setCurrentDirectory(new java.io.File("C:\\Documents"));
        jFileChooser.setDialogTitle("Elige un documento para cargar");
        jFileChooser.setFileHidingEnabled(true);
        jPanel1.add(jFileChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jButtonSubir.setBackground(new java.awt.Color(0, 0, 153));
        jButtonSubir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonSubir.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSubir.setText("Subir archivo");
        jButtonSubir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubirActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSubir, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, 170, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1500, 880));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVolver2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolver2ActionPerformed

        Informes informes = new Informes();
        informes.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButtonVolver2ActionPerformed

    private void jButtonSubirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubirActionPerformed
        
    

    
        
    }//GEN-LAST:event_jButtonSubirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CargarDocumento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CargarDocumento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CargarDocumento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CargarDocumento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CargarDocumento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSubir;
    private javax.swing.JButton jButtonVolver2;
    private javax.swing.JFileChooser jFileChooser;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
