package Daniela.ComexApp.Frames;

import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Date;
import java.time.LocalDate;
import java.time.Month;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import service.EnvioMailImpl;
import service.MailImpl;
import service.PDFContactosImpl;
import service.PDFContenedoresImpl;
import service.PDFOperacionesImpl;
import service.PDFProduccionImpl;

/**
 *
 * @author Daniela
 */
public class EnvioMailConPDF extends javax.swing.JFrame {

     String usuario = "", rol = "", nombreCompleto = "";
    /**
     * Creates new form EnvioMailConPDF
     */
    public EnvioMailConPDF() {
        initComponents();
        
        setSize(1300, 550);
        setLayout(null);
        setLocationRelativeTo(null);
        setResizable(false);
        
        PaginaPrincipal paginaPrincipal = new PaginaPrincipal();
        
        usuario = paginaPrincipal.usuario;
        nombreCompleto = paginaPrincipal.nombreCompleto;
        
        setTitle("Envio de mails - " + usuario + " - sistema ComexApp");
        
    }

    // icono
    public Image getLogo(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/loguito1.png"));
        return retValue;   
    }
    
    
    MailImpl mail = new MailImpl();
    EnvioMailImpl envioMail = new EnvioMailImpl();
    
    PDFContactosImpl pdfContactos = new PDFContactosImpl();
    PDFProduccionImpl pdfProduccion = new PDFProduccionImpl();
    PDFOperacionesImpl pdfOperaciones = new PDFOperacionesImpl();
    PDFContenedoresImpl pdfContenedores = new PDFContenedoresImpl();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonVolver2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textMailOrigen = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textMailDestino = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textContraseña = new javax.swing.JTextField();
        jButtonInfo = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        textAsunto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textMensaje = new javax.swing.JTextArea();
        jButtonEnvio = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        textNombre = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textEspacio1 = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        textEspacio2 = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        textNombreAdjunto = new javax.swing.JTextField();
        jButtonAdjuntar = new javax.swing.JButton();
        cmbPDF = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getLogo());
        setIconImages(getIconImages());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonVolver2.setBackground(new java.awt.Color(0, 0, 153));
        jButtonVolver2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonVolver2.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVolver2.setText("Volver a página principal");
        jButtonVolver2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolver2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonVolver2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, 260, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Envio de mail");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setText("Mail de orígen:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, -1));

        textMailOrigen.setForeground(new java.awt.Color(0, 0, 153));
        jPanel1.add(textMailOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 160, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 153));
        jLabel3.setText("Mail de destino:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, -1, -1));

        textMailDestino.setForeground(new java.awt.Color(0, 0, 153));
        jPanel1.add(textMailDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 160, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 153));
        jLabel4.setText("Contraseña:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));

        textContraseña.setForeground(new java.awt.Color(0, 0, 153));
        jPanel1.add(textContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 160, -1));

        jButtonInfo.setBackground(new java.awt.Color(0, 0, 153));
        jButtonInfo.setForeground(new java.awt.Color(255, 255, 255));
        jButtonInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/preg.png"))); // NOI18N
        jButtonInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInfoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 60, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 153));
        jLabel5.setText("Asunto:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, -1, 20));

        textAsunto.setForeground(new java.awt.Color(0, 0, 153));
        jPanel1.add(textAsunto, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 160, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 153));
        jLabel6.setText("Mensaje:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, -1, 20));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setHorizontalScrollBar(null);

        textMensaje.setColumns(5);
        textMensaje.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        textMensaje.setForeground(new java.awt.Color(0, 0, 153));
        textMensaje.setLineWrap(true);
        textMensaje.setRows(5);
        textMensaje.setTabSize(5);
        textMensaje.setWrapStyleWord(true);
        jScrollPane1.setViewportView(textMensaje);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 400, 180));

        jButtonEnvio.setBackground(new java.awt.Color(0, 0, 153));
        jButtonEnvio.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonEnvio.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEnvio.setText("Enviar mail");
        jButtonEnvio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnvioActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEnvio, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 230, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 153));
        jLabel7.setText("Nombre remitente:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 100, -1, 20));

        textNombre.setForeground(new java.awt.Color(0, 0, 153));
        jPanel1.add(textNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 120, 130, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 153));
        jLabel8.setText("PDF espacio 1:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 20, -1, 20));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setHorizontalScrollBar(null);

        textEspacio1.setColumns(5);
        textEspacio1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        textEspacio1.setForeground(new java.awt.Color(0, 0, 153));
        textEspacio1.setLineWrap(true);
        textEspacio1.setRows(5);
        textEspacio1.setTabSize(5);
        textEspacio1.setWrapStyleWord(true);
        jScrollPane2.setViewportView(textEspacio1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 40, 400, 180));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 153));
        jLabel9.setText("PDF espacio 2:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 230, -1, 20));

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setHorizontalScrollBar(null);

        textEspacio2.setColumns(5);
        textEspacio2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        textEspacio2.setForeground(new java.awt.Color(0, 0, 153));
        textEspacio2.setLineWrap(true);
        textEspacio2.setRows(5);
        textEspacio2.setTabSize(5);
        textEspacio2.setWrapStyleWord(true);
        jScrollPane3.setViewportView(textEspacio2);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 250, 400, 180));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 153));
        jLabel10.setText("En estos espacios podrás escribir o copiar y pegar lo que necesites");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 440, -1, 20));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 153));
        jLabel11.setText("Nombre del PDF:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, -1, 20));

        textNombreAdjunto.setForeground(new java.awt.Color(0, 0, 153));
        jPanel1.add(textNombreAdjunto, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 160, -1));

        jButtonAdjuntar.setBackground(new java.awt.Color(0, 0, 153));
        jButtonAdjuntar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonAdjuntar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAdjuntar.setText("Adjuntar PDF");
        jButtonAdjuntar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdjuntarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAdjuntar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 390, 160, 25));

        cmbPDF.setForeground(new java.awt.Color(0, 0, 153));
        cmbPDF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ninguno", "Contactos", "Operaciones", "Producción", "Contenedores" }));
        cmbPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPDFActionPerformed(evt);
            }
        });
        jPanel1.add(cmbPDF, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 390, 130, 25));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1500, 880));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVolver2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolver2ActionPerformed

        PaginaPrincipal paginaPrincipal = new PaginaPrincipal();
        paginaPrincipal.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButtonVolver2ActionPerformed

    private void jButtonInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInfoActionPerformed

        InformacionMail infoMail = new InformacionMail();
        infoMail.setVisible(true);
        
    }//GEN-LAST:event_jButtonInfoActionPerformed

    private void jButtonEnvioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnvioActionPerformed
        
        String correoOrigen, correoDestino, asunto, mensaje, contraseña, 
                nombreRemitente, espacio1, espacio2, nombreAdjunto;
        Boolean envioHTML, mailEnviado;
        
        correoOrigen = textMailOrigen.getText().trim();
        correoDestino = textMailDestino.getText().trim();
        asunto = textAsunto.getText().trim();
        mensaje = textMensaje.getText().trim();
        contraseña = textContraseña.getText().trim();
        nombreRemitente = textNombre.getText().trim();
        espacio1 = textEspacio1.getText().trim();
        espacio2 = textEspacio2.getText().trim();
        nombreAdjunto = textNombreAdjunto.getText().trim();
        
        if(!correoOrigen.equals(null) && !correoDestino.equals(null) && !asunto.equals(null)
                && !mensaje.equals(null) && !contraseña.equals(null) && !nombreRemitente.equals(null)){
            envioHTML = true;
        } else {
            envioHTML = false;
        }
        
        
        try {
             //mail.envioDeMensajes(correoOrigen, correoDestino, asunto, mensaje, contraseña);
            mailEnviado = envioMail.enviarEmailAnexo(envioHTML, correoOrigen, contraseña, correoDestino,
                     nombreRemitente, asunto, mensaje, nombreAdjunto, espacio1, espacio2);
             
            if(mailEnviado.equals(true)){
            JOptionPane.showMessageDialog(null, "Mensaje enviado", "Envio de mails", 0);
           }
             
        } catch (Exception e) {
             System.err.print("Error al enviar mail con adjunto " + e);
    }
        
    }//GEN-LAST:event_jButtonEnvioActionPerformed

    private void jButtonAdjuntarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdjuntarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAdjuntarActionPerformed

    private void cmbPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPDFActionPerformed
        
        int eleccion = cmbPDF.getSelectedIndex() + 1;
        
        if(eleccion != 1){
            
            int diaN = LocalDate.now().getDayOfMonth();
            Month mesN = LocalDate.now().getMonth();
            int añoN = LocalDate.now().getYear();

            String dia = String.valueOf(diaN);
            String mes = String.valueOf(mesN);
            String año = String.valueOf(añoN);
            
            if(eleccion == 2){
                pdfContactos.pdfTodosLosContactos(usuario, nombreCompleto, dia, mes, año);
            } else if (eleccion == 3){
                pdfOperaciones.pdfTodasLasOperaciones(usuario, nombreCompleto, dia, mes, año);
            } else if (eleccion == 4){
                pdfProduccion.pdfTodoDeProduccion(usuario, nombreCompleto, dia, mes, año);
            } else if (eleccion == 5){
                pdfContenedores.pdfContenedores(usuario, nombreCompleto, dia, mes, año);
            }
            
        } 
    }//GEN-LAST:event_cmbPDFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnvioMailConPDF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnvioMailConPDF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnvioMailConPDF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnvioMailConPDF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EnvioMailConPDF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbPDF;
    private javax.swing.JButton jButtonAdjuntar;
    private javax.swing.JButton jButtonEnvio;
    private javax.swing.JButton jButtonInfo;
    private javax.swing.JButton jButtonVolver2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField textAsunto;
    private javax.swing.JTextField textContraseña;
    private javax.swing.JTextArea textEspacio1;
    private javax.swing.JTextArea textEspacio2;
    private javax.swing.JTextField textMailDestino;
    private javax.swing.JTextField textMailOrigen;
    private javax.swing.JTextArea textMensaje;
    private javax.swing.JTextField textNombre;
    private javax.swing.JTextField textNombreAdjunto;
    // End of variables declaration//GEN-END:variables
}
