package Daniela.ComexApp.Frames;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import service.ReportesEstadisticasExportacionesImpl;
import service.ReportesEstadisticasGeneralesImpl;
import service.ReportesEstadisticasImportacionesImpl;

/**
 *
 * @author Daniela
 */
public class EstadisticasGeneralesOperaciones extends javax.swing.JFrame {

     String usuario = "", rol = "", nombreCompleto = "";
    /**
     * Creates new form EstadisticasGeneralesOperaciones
     */
    public EstadisticasGeneralesOperaciones() {
        initComponents();
        
        setSize(1100, 800);
        setLayout(null);
        setLocationRelativeTo(null);
        setResizable(false);
        
        PaginaPrincipal paginaPrincipal = new PaginaPrincipal();
        
        usuario = paginaPrincipal.usuario;
        nombreCompleto = paginaPrincipal.nombreCompleto;
        
        setTitle("Estadísticas de operaciones internacionales- " + usuario + " - sistema ComexApp");
        repaint();    
        
        jLabelExpos.setText("Exportaciones: " + totalExpos);
        jLabelImpos.setText("Importaciones: " + totalImpos);
        jLabelTotal.setText("Total operaciones: " + totalOpsInternac);
        
        jLabelEmpresaExportadora.setText("Mayores ventas a: " + empresaExportadoraMasRepetida);
        jLabelEmpresaImportadora.setText("Mayores compras a: " + empresaImportadoraMasRepetida);
        jLabelProductosMasExportado.setText("Producto más exportado: " + productoMasExportado);
        jLabelProductosMasImportado.setText("Producto más importado: " + productoMasImportado);
    }

    // icono
    public Image getLogo(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/loguito1.png"));
        return retValue;   
    }
    
    ReportesEstadisticasExportacionesImpl reportesExpos = new ReportesEstadisticasExportacionesImpl();
    int totalExpos = reportesExpos.cantidadDeOperacionesDeExportacionTotales();
    String empresaExportadoraMasRepetida = reportesExpos.compradorMasRepetido();
    String productoMasExportado = reportesExpos.productoMasExportado();
    
    ReportesEstadisticasImportacionesImpl reportesImpos = new ReportesEstadisticasImportacionesImpl();
    int totalImpos = reportesImpos.cantidadDeOperacionesDeImportacionTotales();
    String empresaImportadoraMasRepetida = reportesImpos.vendedorMasRepetido();
    String productoMasImportado = reportesImpos.productoMasImportado();
    
    
    ReportesEstadisticasGeneralesImpl reportesOperacionesInternacionales = new ReportesEstadisticasGeneralesImpl();
    int totalOpsInternac = reportesOperacionesInternacionales.cantidadDeOperacionesInternacionalesRegistradas();
    
    
    
    int porcentajeExpos = PorcentajeExportacionesRegistradas(totalExpos, totalOpsInternac);
   
        
    public int PorcentajeExportacionesRegistradas(int totalExpos, int totalOpsInternac){
        int porcentajeExpos = totalExpos / totalOpsInternac;
        return porcentajeExpos; 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonVolver2 = new javax.swing.JButton();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelExpos = new javax.swing.JLabel();
        jLabelTotal = new javax.swing.JLabel();
        jLabelImpos = new javax.swing.JLabel();
        jLabelEmpresaExportadora = new javax.swing.JLabel();
        jLabelEmpresaImportadora = new javax.swing.JLabel();
        jLabelProductosMasExportado = new javax.swing.JLabel();
        jLabelProductosMasImportado = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButtonListaProductos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getLogo());
        setIconImages(getIconImages());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonVolver2.setBackground(new java.awt.Color(102, 102, 102));
        jButtonVolver2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonVolver2.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVolver2.setText("Volver");
        jButtonVolver2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolver2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonVolver2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 680, 94, -1));

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("Operaciones internacionales");
        jPanel1.add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, -1, -1));

        jLabelExpos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelExpos.setForeground(new java.awt.Color(255, 255, 255));
        jLabelExpos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cubo.png"))); // NOI18N
        jLabelExpos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabelExpos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 200, 200));

        jLabelTotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelTotal.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTotal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cubo.png"))); // NOI18N
        jLabelTotal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabelTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, -1, -1));

        jLabelImpos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelImpos.setForeground(new java.awt.Color(255, 255, 255));
        jLabelImpos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cubo.png"))); // NOI18N
        jLabelImpos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabelImpos, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 240, -1, -1));

        jLabelEmpresaExportadora.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelEmpresaExportadora.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEmpresaExportadora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cuadrito.png"))); // NOI18N
        jLabelEmpresaExportadora.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabelEmpresaExportadora, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, -1, 80));

        jLabelEmpresaImportadora.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelEmpresaImportadora.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEmpresaImportadora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cuadrito.png"))); // NOI18N
        jLabelEmpresaImportadora.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabelEmpresaImportadora, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 470, 250, 80));

        jLabelProductosMasExportado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelProductosMasExportado.setForeground(new java.awt.Color(255, 255, 255));
        jLabelProductosMasExportado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/rectangulo.png"))); // NOI18N
        jLabelProductosMasExportado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabelProductosMasExportado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, -1, 80));

        jLabelProductosMasImportado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelProductosMasImportado.setForeground(new java.awt.Color(255, 255, 255));
        jLabelProductosMasImportado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/rectangulo.png"))); // NOI18N
        jLabelProductosMasImportado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabelProductosMasImportado, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 560, -1, 80));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonListaProductos.setBackground(new java.awt.Color(102, 102, 102));
        jButtonListaProductos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonListaProductos.setForeground(new java.awt.Color(255, 255, 255));
        jButtonListaProductos.setText("Lista productos");
        jButtonListaProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListaProductosActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonListaProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 170, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cuadro.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 10, 220, 490));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 180, 210, 520));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1500, 880));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVolver2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolver2ActionPerformed

        Informes informes = new Informes();
        informes.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButtonVolver2ActionPerformed

    private void jButtonListaProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListaProductosActionPerformed
        
        EstadisticasProductos productos = new EstadisticasProductos();
        productos.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButtonListaProductosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EstadisticasGeneralesOperaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EstadisticasGeneralesOperaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EstadisticasGeneralesOperaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EstadisticasGeneralesOperaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EstadisticasGeneralesOperaciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonListaProductos;
    private javax.swing.JButton jButtonVolver2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelEmpresaExportadora;
    private javax.swing.JLabel jLabelEmpresaImportadora;
    private javax.swing.JLabel jLabelExpos;
    private javax.swing.JLabel jLabelImpos;
    private javax.swing.JLabel jLabelProductosMasExportado;
    private javax.swing.JLabel jLabelProductosMasImportado;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables


    public int OperacionMasNumerosa (int totalExpos, int totalImpos){
       
        int operacionMasRepetida = 0;
        
        if(totalExpos > totalImpos){
            return totalExpos;
        } else if (totalImpos > totalExpos){
            return totalImpos;
        }
        return operacionMasRepetida;
    }
     
    int operacionMasRepetida = OperacionMasNumerosa(totalExpos, totalImpos);
    
  @Override
    public void paint(Graphics g){
        super.paint(g);

        int largoExpos = totalExpos * 400 / operacionMasRepetida;
        int largoImpos = totalImpos * 400 / operacionMasRepetida;
        
        g.setColor(new Color(255, 255, 255));
        g.fillRect(100, 80, largoExpos, 40);
        g.drawString("Exportaciones registradas: " + totalExpos, 100, 70);
        
        g.setColor(new Color(204,204,204));
        g.fillRect(100, 150, largoImpos, 40);
        g.drawString("Importaciones registras: " + totalImpos , 100, 145);
        
    }


}
