package Daniela.ComexApp.Frames;

import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Date;
import java.time.LocalDate;
import service.ContenedoresImpl;


/**
 *
 * @author Daniela
 */
public class IngresarContenedor extends javax.swing.JFrame {

     String usuario = "", nombreCompleto = "";
    /**
     * Creates new form IngresarContenedor
     */
    public IngresarContenedor() {
        initComponents();
        
        setSize(800, 460);
        setLayout(null);
        setLocationRelativeTo(null);
        setResizable(false);
        
        PaginaPrincipal paginaPrincipal = new PaginaPrincipal();
        
        usuario = paginaPrincipal.usuario;
        nombreCompleto = paginaPrincipal.nombreCompleto;
        
        setTitle("Ingresar contenedor - " + usuario + " - sistema ComexApp");
    }
    // icono
    public Image getLogo(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/loguito1.png"));
        return retValue;   
    }
    
    ContenedoresImpl contenedoresImpl = new ContenedoresImpl();

    
    Date fechaUltimo, fechaProximo;

    
    public void LimpiarCampos(){
        textID.setText("");
        textCantidad.setText("");
        textCodigo.setText("");
        textCapacidad.setText("");
        textProducto.setText("");
        textTipo.setText("");
        cmbStatus.setSelectedIndex(0);
        textEmpresa.setText("");
        textReserva.setText("");
        textCompañia.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonIngresar = new javax.swing.JButton();
        jPanelRegistro = new javax.swing.JPanel();
        jLabelID = new javax.swing.JLabel();
        textID = new javax.swing.JTextField();
        jButtonInfo = new javax.swing.JButton();
        jLabelProductos = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textProducto = new javax.swing.JTextArea();
        jLabelCodigo = new javax.swing.JLabel();
        textCodigo = new javax.swing.JTextField();
        jLabelContenedores = new javax.swing.JLabel();
        textCantidad = new javax.swing.JTextField();
        jLabelCantidad = new javax.swing.JLabel();
        textTipo = new javax.swing.JTextField();
        jLabelNumero = new javax.swing.JLabel();
        textCapacidad = new javax.swing.JTextField();
        jLabelStatus = new javax.swing.JLabel();
        cmbStatus = new javax.swing.JComboBox<>();
        jLabelComprador = new javax.swing.JLabel();
        textEmpresa = new javax.swing.JTextField();
        jLabelVendedor = new javax.swing.JLabel();
        textReserva = new javax.swing.JTextField();
        jLabelNombreBuque = new javax.swing.JLabel();
        textCompañia = new javax.swing.JTextField();
        jLabelCodigo1 = new javax.swing.JLabel();
        jLabelCodigo2 = new javax.swing.JLabel();
        jButtonAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getLogo());
        setIconImages(getIconImages());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonIngresar.setBackground(new java.awt.Color(0, 0, 153));
        jButtonIngresar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonIngresar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonIngresar.setText("Ingresar producto al sistema");
        jButtonIngresar.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jButtonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIngresarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, -1, -1));

        jPanelRegistro.setBackground(new java.awt.Color(204, 204, 204));
        jPanelRegistro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelID.setForeground(new java.awt.Color(0, 0, 153));
        jLabelID.setText("ID:");
        jPanelRegistro.add(jLabelID, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        textID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textID.setForeground(new java.awt.Color(0, 0, 153));
        textID.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelRegistro.add(textID, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 60, -1));

        jButtonInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/signo4.png"))); // NOI18N
        jButtonInfo.setBorder(null);
        jButtonInfo.setBorderPainted(false);
        jButtonInfo.setContentAreaFilled(false);
        jButtonInfo.setFocusPainted(false);
        jButtonInfo.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/signo5.png"))); // NOI18N
        jButtonInfo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/signo5.png"))); // NOI18N
        jButtonInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInfoActionPerformed(evt);
            }
        });
        jPanelRegistro.add(jButtonInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        jLabelProductos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelProductos.setForeground(new java.awt.Color(0, 0, 153));
        jLabelProductos.setText("Productos:");
        jPanelRegistro.add(jLabelProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setForeground(new java.awt.Color(0, 0, 153));
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        textProducto.setColumns(10);
        textProducto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textProducto.setForeground(new java.awt.Color(0, 0, 153));
        textProducto.setLineWrap(true);
        textProducto.setRows(5);
        textProducto.setWrapStyleWord(true);
        jScrollPane2.setViewportView(textProducto);

        jPanelRegistro.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 150, 120));

        jLabelCodigo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelCodigo.setForeground(new java.awt.Color(0, 0, 153));
        jLabelCodigo.setText("Código contenedor:");
        jPanelRegistro.add(jLabelCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, -1, -1));

        textCodigo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textCodigo.setForeground(new java.awt.Color(0, 0, 153));
        textCodigo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelRegistro.add(textCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 163, 30));

        jLabelContenedores.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelContenedores.setForeground(new java.awt.Color(0, 0, 153));
        jLabelContenedores.setText("Cantidad de productos:");
        jPanelRegistro.add(jLabelContenedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, -1, -1));

        textCantidad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textCantidad.setForeground(new java.awt.Color(0, 0, 153));
        textCantidad.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelRegistro.add(textCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 163, 30));

        jLabelCantidad.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelCantidad.setForeground(new java.awt.Color(0, 0, 153));
        jLabelCantidad.setText("Tipo de contenedor:");
        jPanelRegistro.add(jLabelCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 140, -1));

        textTipo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textTipo.setForeground(new java.awt.Color(0, 0, 153));
        textTipo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelRegistro.add(textTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 160, 30));

        jLabelNumero.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelNumero.setForeground(new java.awt.Color(0, 0, 153));
        jLabelNumero.setText("Capacidad real:");
        jPanelRegistro.add(jLabelNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, -1, -1));

        textCapacidad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textCapacidad.setForeground(new java.awt.Color(0, 0, 153));
        textCapacidad.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelRegistro.add(textCapacidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 150, 30));

        jLabelStatus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelStatus.setForeground(new java.awt.Color(0, 0, 153));
        jLabelStatus.setText("Status:");
        jPanelRegistro.add(jLabelStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        cmbStatus.setForeground(new java.awt.Color(0, 0, 153));
        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Disponible ", "Reservado", "En uso", "No disponible", "En reparación", "En control", "En limpieza", "Fuera de circulación" }));
        cmbStatus.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmbStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbStatusActionPerformed(evt);
            }
        });
        jPanelRegistro.add(cmbStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 120, 40));

        jLabelComprador.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelComprador.setForeground(new java.awt.Color(0, 0, 153));
        jLabelComprador.setText("Empresa:");
        jPanelRegistro.add(jLabelComprador, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 100, -1));

        textEmpresa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textEmpresa.setForeground(new java.awt.Color(0, 0, 153));
        textEmpresa.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelRegistro.add(textEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 130, 30));

        jLabelVendedor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelVendedor.setForeground(new java.awt.Color(0, 0, 153));
        jLabelVendedor.setText("Reserva:");
        jPanelRegistro.add(jLabelVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 100, -1));

        textReserva.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textReserva.setForeground(new java.awt.Color(0, 0, 153));
        textReserva.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelRegistro.add(textReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 160, 30));

        jLabelNombreBuque.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelNombreBuque.setForeground(new java.awt.Color(0, 0, 153));
        jLabelNombreBuque.setText("Compañia transporte:");
        jPanelRegistro.add(jLabelNombreBuque, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, -1, -1));

        textCompañia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textCompañia.setForeground(new java.awt.Color(0, 0, 153));
        textCompañia.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelRegistro.add(textCompañia, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 150, 30));

        jLabelCodigo1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelCodigo1.setForeground(new java.awt.Color(0, 0, 153));
        jLabelCodigo1.setText("Información importante:");
        jPanelRegistro.add(jLabelCodigo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        jLabelCodigo2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelCodigo2.setForeground(new java.awt.Color(0, 0, 153));
        jLabelCodigo2.setText("las fechas de los controles por defecto serán la fecha actual y dentro de un año y un mes.");
        jPanelRegistro.add(jLabelCodigo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 312, -1, -1));

        jPanel1.add(jPanelRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 750, 330));

        jButtonAtras.setBackground(new java.awt.Color(0, 0, 153));
        jButtonAtras.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonAtras.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAtras.setText("Volver atrás");
        jButtonAtras.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jButtonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtrasActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 370, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 983, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIngresarActionPerformed

        try {
            String codigo, empresa, producto, tipo, compañiaTransporte, reserva, status = null;

            int statusNivel = 0, ID, cantidad;
            Double capacidad;
            Date fechaUltimo, fechaProximo;
           
            Boolean recepcionFuncion;
            
            ID = Integer.parseInt(textID.getText().trim());
            cantidad = Integer.parseInt(textCantidad.getText().trim());
            capacidad = Double.valueOf(textCapacidad.getText().trim());

            codigo = textCodigo.getText().trim();
            empresa = textEmpresa.getText().trim();
            producto = textProducto.getText().trim();
            tipo = textTipo.getText().trim();
            compañiaTransporte = textCompañia.getText().trim();
            reserva = textReserva.getText().trim();

            fechaUltimo = Date.valueOf(LocalDate.now());
            fechaProximo = Date.valueOf(fechaUltimo.toLocalDate().plusYears(1).plusMonths(1));
            
            statusNivel = cmbStatus.getSelectedIndex() + 1;
            
            if (statusNivel == 1) {
                status = "Disponible";
            } else if (statusNivel == 2) {
                status = "Reservado";
            } else if (statusNivel == 3) {
                status = "En uso";
            } else if (statusNivel == 4) {
                status = "No disponible";
            } else if (statusNivel == 5) {
                status = "En reparación";
            } else if (statusNivel == 6) {
                status = "En control";
            } else if (statusNivel == 7) {
                status = "En limpieza";
            } else if (statusNivel == 8) {
                status = "Fuera de circulación";
            }

            recepcionFuncion = contenedoresImpl.registrarContenedor(ID, cantidad,
                    capacidad, codigo, empresa, producto, tipo, compañiaTransporte,
                    fechaProximo, reserva, status, fechaUltimo);

           if (recepcionFuncion.equals(true)) {
                LimpiarCampos();
           }

        
        } catch (Exception e) {
            System.err.print("No es posible registrar " + e);
        } 

    }//GEN-LAST:event_jButtonIngresarActionPerformed

    private void jButtonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtrasActionPerformed

        this.dispose();
        
    }//GEN-LAST:event_jButtonAtrasActionPerformed

    private void cmbStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbStatusActionPerformed

    private void jButtonInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInfoActionPerformed

        InformacionIDContenedor informacionIDContenedor = new InformacionIDContenedor();
        informacionIDContenedor.setVisible(true);

    }//GEN-LAST:event_jButtonInfoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresarContenedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresarContenedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresarContenedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresarContenedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IngresarContenedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JButton jButtonAtras;
    private javax.swing.JButton jButtonInfo;
    private javax.swing.JButton jButtonIngresar;
    private javax.swing.JLabel jLabelCantidad;
    private javax.swing.JLabel jLabelCodigo;
    private javax.swing.JLabel jLabelCodigo1;
    private javax.swing.JLabel jLabelCodigo2;
    private javax.swing.JLabel jLabelComprador;
    private javax.swing.JLabel jLabelContenedores;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelNombreBuque;
    private javax.swing.JLabel jLabelNumero;
    private javax.swing.JLabel jLabelProductos;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JLabel jLabelVendedor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelRegistro;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField textCantidad;
    private javax.swing.JTextField textCapacidad;
    private javax.swing.JTextField textCodigo;
    private javax.swing.JTextField textCompañia;
    private javax.swing.JTextField textEmpresa;
    private javax.swing.JTextField textID;
    private javax.swing.JTextArea textProducto;
    private javax.swing.JTextField textReserva;
    private javax.swing.JTextField textTipo;
    // End of variables declaration//GEN-END:variables
}
