package Daniela.ComexApp.Frames;

import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Date;
import javax.swing.JOptionPane;
import service.GastosImpl;


/**
 *
 * @author Daniela
 */
public class IngresarGasto extends javax.swing.JFrame {

     String usuario = "", nombreCompleto = "";
    /**
     * Creates new form IngresarGasto
     */
    public IngresarGasto() {
        initComponents();
        
        setSize(650, 460);
        setLayout(null);
        setLocationRelativeTo(null);
        setResizable(false);
        
        PaginaPrincipal paginaPrincipal = new PaginaPrincipal();
        
        usuario = paginaPrincipal.usuario;
        nombreCompleto = paginaPrincipal.nombreCompleto;
        
        setTitle("Ingresar gasto - " + usuario + " - sistema ComexApp");
        
       /* if (!textTotal.equals("")) {

        } else {
            Double gastosTotales = Double.valueOf(textTotal.getText().trim());
            int cuotas = cmbCuotas.getSelectedIndex() + 1;
            Double cuotasCalculadas;
            while (gastosTotales != 0 && cuotas != 0) {
                cuotasCalculadas = calculoCuotas(gastosTotales, cuotas);
                textValorCuotas.setText(String.valueOf(cuotasCalculadas));

            }
        }
*/

    }
    // icono
    public Image getLogo(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/loguito1.png"));
        return retValue;   
    }
    
    Date fechaActual;

    GastosImpl gastos = new GastosImpl();

    
    
    public Double calculoCuotas(double gastosTotales, int cuotas){
       
        Double monto = gastosTotales / cuotas;
        
        return monto;
    }
    
    public double calculoPrecioTotal(double valorCuotas, int cuotas, double intereses){
        
        Double cuotasD = Double.valueOf(cuotas);
        Double total = cuotasD * (valorCuotas + intereses);
        
        return total;
    }
    
    public double calculoFaltante(double gastosTotales, double pagado){
        
        Double faltante = gastosTotales - pagado;
        return faltante;
    }
    
    public double obtenerElTotal(){
       
        Double montoCuotas = Double.valueOf(textValorCuotas.getText().trim());
        int cuotas = cmbCuotas.getSelectedIndex() + 1;
        Double intereses = Double.valueOf(textIntereses.getText().trim());
        
        double total = calculoPrecioTotal(montoCuotas, cuotas, intereses);
        return total;
    }

    public double calcularValorPagado() {
        int cuotasP = cmbCuotasP.getSelectedIndex() + 1;
        int cuotas = cmbCuotas.getSelectedIndex() + 1;

        double total = Double.valueOf(textTotal.getText().trim());

        double cuotasValor = calculoCuotas(total, cuotas);
        double valorPagado = cuotasValor * cuotasP;
        double valorMaximo = cuotasValor * 24;
        
        if(cuotas >= cuotasP){
            return valorPagado;
        } else {
            JOptionPane.showMessageDialog(null, "Las cuotas pagadas son superiores "
                    + "a las cuotas asignadas");
            return valorPagado = 0;
        }
        
    }

    public void LimpiarCampos(){
        textValorCuotas.setText("");
        textTotal.setText("");
        textConcepto.setText("");
        textPagado.setText("");
        textDetalles.setText("");
        textSinPagar.setText("");
        cmbStatus.setSelectedIndex(0);
        cmbCuotas.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonIngresar = new javax.swing.JButton();
        jPanelRegistro = new javax.swing.JPanel();
        jLabelDetalles = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textDetalles = new javax.swing.JTextArea();
        jLabelConcepto = new javax.swing.JLabel();
        textConcepto = new javax.swing.JTextField();
        jLabelValor = new javax.swing.JLabel();
        textTotal = new javax.swing.JTextField();
        jLabelStatus = new javax.swing.JLabel();
        cmbStatus = new javax.swing.JComboBox<>();
        jLabelCodigo1 = new javax.swing.JLabel();
        jLabelCodigo2 = new javax.swing.JLabel();
        jLabelPagado = new javax.swing.JLabel();
        textPagado = new javax.swing.JTextField();
        jLabelSinPagar = new javax.swing.JLabel();
        textSinPagar = new javax.swing.JTextField();
        jLabelCuotas = new javax.swing.JLabel();
        cmbCuotas = new javax.swing.JComboBox<>();
        jLabelValorCuotas = new javax.swing.JLabel();
        textValorCuotas = new javax.swing.JTextField();
        jButtonCalcularCuotas = new javax.swing.JButton();
        jLabelCuotas1 = new javax.swing.JLabel();
        textIntereses = new javax.swing.JTextField();
        jButtonCalcularTotal = new javax.swing.JButton();
        jButtonCalcularFaltante = new javax.swing.JButton();
        jButtonCalcularFaltante1 = new javax.swing.JButton();
        jLabelCuotas2 = new javax.swing.JLabel();
        cmbCuotasP = new javax.swing.JComboBox<>();
        jButtonCalcularPagado = new javax.swing.JButton();
        jButtonAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getLogo());
        setIconImages(getIconImages());
        setPreferredSize(new java.awt.Dimension(650, 459));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonIngresar.setBackground(new java.awt.Color(0, 0, 153));
        jButtonIngresar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonIngresar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonIngresar.setText("Ingresar gasto");
        jButtonIngresar.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jButtonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIngresarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, -1, -1));

        jPanelRegistro.setBackground(new java.awt.Color(204, 204, 204));
        jPanelRegistro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelDetalles.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelDetalles.setForeground(new java.awt.Color(0, 0, 153));
        jLabelDetalles.setText("Detalles:");
        jPanelRegistro.add(jLabelDetalles, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setForeground(new java.awt.Color(0, 0, 153));
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        textDetalles.setColumns(10);
        textDetalles.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textDetalles.setForeground(new java.awt.Color(0, 0, 153));
        textDetalles.setLineWrap(true);
        textDetalles.setRows(5);
        textDetalles.setWrapStyleWord(true);
        jScrollPane2.setViewportView(textDetalles);

        jPanelRegistro.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 160, 120));

        jLabelConcepto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelConcepto.setForeground(new java.awt.Color(0, 0, 153));
        jLabelConcepto.setText("Concepto:");
        jPanelRegistro.add(jLabelConcepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        textConcepto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textConcepto.setForeground(new java.awt.Color(0, 0, 153));
        textConcepto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelRegistro.add(textConcepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 163, 30));

        jLabelValor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelValor.setForeground(new java.awt.Color(0, 0, 153));
        jLabelValor.setText("Total:");
        jPanelRegistro.add(jLabelValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, -1, -1));

        textTotal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textTotal.setForeground(new java.awt.Color(0, 0, 153));
        textTotal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelRegistro.add(textTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 163, 30));

        jLabelStatus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelStatus.setForeground(new java.awt.Color(0, 0, 153));
        jLabelStatus.setText("Status:");
        jPanelRegistro.add(jLabelStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        cmbStatus.setForeground(new java.awt.Color(0, 0, 153));
        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pago completo", "Pagado en partes", "Pago en cuotas", "Sin pagar" }));
        cmbStatus.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmbStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbStatusActionPerformed(evt);
            }
        });
        jPanelRegistro.add(cmbStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 160, 30));

        jLabelCodigo1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelCodigo1.setForeground(new java.awt.Color(0, 0, 153));
        jLabelCodigo1.setText("Información importante:");
        jPanelRegistro.add(jLabelCodigo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        jLabelCodigo2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelCodigo2.setForeground(new java.awt.Color(0, 0, 153));
        jLabelCodigo2.setText("la fecha de registro por defecto será la fecha actual");
        jPanelRegistro.add(jLabelCodigo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 312, -1, -1));

        jLabelPagado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelPagado.setForeground(new java.awt.Color(0, 0, 153));
        jLabelPagado.setText("Pagado:");
        jPanelRegistro.add(jLabelPagado, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, -1, -1));

        textPagado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textPagado.setForeground(new java.awt.Color(0, 0, 153));
        textPagado.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelRegistro.add(textPagado, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 163, 30));

        jLabelSinPagar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelSinPagar.setForeground(new java.awt.Color(0, 0, 153));
        jLabelSinPagar.setText("Sin pagar:");
        jPanelRegistro.add(jLabelSinPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, -1, 20));

        textSinPagar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textSinPagar.setForeground(new java.awt.Color(0, 0, 153));
        textSinPagar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelRegistro.add(textSinPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, 163, 30));

        jLabelCuotas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelCuotas.setForeground(new java.awt.Color(0, 0, 153));
        jLabelCuotas.setText("Cuotas:");
        jPanelRegistro.add(jLabelCuotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, -1, -1));

        cmbCuotas.setForeground(new java.awt.Color(0, 0, 153));
        cmbCuotas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24" }));
        cmbCuotas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmbCuotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCuotasActionPerformed(evt);
            }
        });
        jPanelRegistro.add(cmbCuotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 50, 30));

        jLabelValorCuotas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelValorCuotas.setForeground(new java.awt.Color(0, 0, 153));
        jLabelValorCuotas.setText("Valor de cuotas:");
        jPanelRegistro.add(jLabelValorCuotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, -1));

        textValorCuotas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textValorCuotas.setForeground(new java.awt.Color(0, 0, 153));
        textValorCuotas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelRegistro.add(textValorCuotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 150, 30));

        jButtonCalcularCuotas.setBackground(new java.awt.Color(0, 0, 153));
        jButtonCalcularCuotas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonCalcularCuotas.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCalcularCuotas.setText("Calcular cuotas");
        jButtonCalcularCuotas.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jButtonCalcularCuotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcularCuotasActionPerformed(evt);
            }
        });
        jPanelRegistro.add(jButtonCalcularCuotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, 160, 30));

        jLabelCuotas1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelCuotas1.setForeground(new java.awt.Color(0, 0, 153));
        jLabelCuotas1.setText("Intereses mensuales:");
        jPanelRegistro.add(jLabelCuotas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, -1, -1));

        textIntereses.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textIntereses.setForeground(new java.awt.Color(0, 0, 153));
        textIntereses.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelRegistro.add(textIntereses, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 150, 30));

        jButtonCalcularTotal.setBackground(new java.awt.Color(0, 0, 153));
        jButtonCalcularTotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonCalcularTotal.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCalcularTotal.setText("Calcular total");
        jButtonCalcularTotal.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jButtonCalcularTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcularTotalActionPerformed(evt);
            }
        });
        jPanelRegistro.add(jButtonCalcularTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 150, 30));

        jButtonCalcularFaltante.setBackground(new java.awt.Color(0, 0, 153));
        jButtonCalcularFaltante.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonCalcularFaltante.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCalcularFaltante.setText("Calcular faltante");
        jButtonCalcularFaltante.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jButtonCalcularFaltante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcularFaltanteActionPerformed(evt);
            }
        });
        jPanelRegistro.add(jButtonCalcularFaltante, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, 160, 30));

        jButtonCalcularFaltante1.setBackground(new java.awt.Color(0, 0, 153));
        jButtonCalcularFaltante1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonCalcularFaltante1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCalcularFaltante1.setText("Calcular faltante");
        jButtonCalcularFaltante1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jButtonCalcularFaltante1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcularFaltante1ActionPerformed(evt);
            }
        });
        jPanelRegistro.add(jButtonCalcularFaltante1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, 160, 30));

        jLabelCuotas2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelCuotas2.setForeground(new java.awt.Color(0, 0, 153));
        jLabelCuotas2.setText("Cuotas pagadas:");
        jPanelRegistro.add(jLabelCuotas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, -1, -1));

        cmbCuotasP.setForeground(new java.awt.Color(0, 0, 153));
        cmbCuotasP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24" }));
        cmbCuotasP.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmbCuotasP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCuotasPActionPerformed(evt);
            }
        });
        jPanelRegistro.add(cmbCuotasP, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 50, 30));

        jButtonCalcularPagado.setBackground(new java.awt.Color(0, 0, 153));
        jButtonCalcularPagado.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonCalcularPagado.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCalcularPagado.setText("Calcular pagado");
        jButtonCalcularPagado.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jButtonCalcularPagado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcularPagadoActionPerformed(evt);
            }
        });
        jPanelRegistro.add(jButtonCalcularPagado, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 150, 30));

        jPanel1.add(jPanelRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 600, 330));

        jButtonAtras.setBackground(new java.awt.Color(0, 0, 153));
        jButtonAtras.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonAtras.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAtras.setText("Volver atrás");
        jButtonAtras.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jButtonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtrasActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 370, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 983, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIngresarActionPerformed

        String conceptos, empresa = null, detalles, status = null;
        Double gastosTotales, gastosPagos, gastosSinPagar, montoCuotas, intereses;
        int cuotas, statusNivel;
  
        gastosTotales = Double.valueOf(textTotal.getText().trim());
        montoCuotas = Double.valueOf(textValorCuotas.getText().trim());
        
        conceptos = textConcepto.getText().trim();
        gastosPagos = Double.parseDouble(textPagado.getText().trim());
        detalles = textDetalles.getText().trim();
        gastosSinPagar = Double.parseDouble(textSinPagar.getText().trim());
        cuotas = cmbCuotas.getSelectedIndex() + 1;
        statusNivel = cmbStatus.getSelectedIndex() + 1;
        
        intereses = Double.valueOf(textIntereses.getText().trim());
        
        if(statusNivel == 1){
            status = "Pago completo";
        } else if(statusNivel == 2){
            status = "Pagado en partes";
        } else if(statusNivel == 3){
            status = "Pago en cuotas";
        } else if(statusNivel == 4){
            status = "Sin pagar";
        }
        
        gastos.registrarGasto(conceptos, empresa, gastosTotales, cuotas, detalles,
                gastosPagos, gastosSinPagar, montoCuotas, intereses, status);
        
    }//GEN-LAST:event_jButtonIngresarActionPerformed

    private void jButtonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtrasActionPerformed

        this.dispose();
        
    }//GEN-LAST:event_jButtonAtrasActionPerformed

    private void cmbStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbStatusActionPerformed

    private void cmbCuotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCuotasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCuotasActionPerformed

    private void jButtonCalcularCuotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcularCuotasActionPerformed
      
        double gastosTotales = Double.valueOf(textTotal.getText().trim());
        int cuotas = cmbCuotas.getSelectedIndex() + 1;
        
        double valorCuotas = calculoCuotas(gastosTotales, cuotas);
        textValorCuotas.setText(String.valueOf(valorCuotas));
        
    }//GEN-LAST:event_jButtonCalcularCuotasActionPerformed

    private void jButtonCalcularTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcularTotalActionPerformed

        double total = obtenerElTotal();
        textTotal.setText(String.valueOf(total));
        
    }//GEN-LAST:event_jButtonCalcularTotalActionPerformed

    private void jButtonCalcularFaltanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcularFaltanteActionPerformed
    
        double gastosTotales = Double.valueOf(textTotal.getText().trim());
        double pagado = Double.parseDouble(textPagado.getText().trim());
        
        double faltante = calculoFaltante(gastosTotales, pagado);
        textSinPagar.setText(String.valueOf(faltante));
        
    }//GEN-LAST:event_jButtonCalcularFaltanteActionPerformed

    private void jButtonCalcularFaltante1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcularFaltante1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCalcularFaltante1ActionPerformed

    private void cmbCuotasPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCuotasPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCuotasPActionPerformed

    private void jButtonCalcularPagadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcularPagadoActionPerformed
        
        double valorPagado = calcularValorPagado();
        textPagado.setText(String.valueOf(valorPagado));
             
    }//GEN-LAST:event_jButtonCalcularPagadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresarGasto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresarGasto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresarGasto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresarGasto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IngresarGasto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbCuotas;
    private javax.swing.JComboBox<String> cmbCuotasP;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JButton jButtonAtras;
    private javax.swing.JButton jButtonCalcularCuotas;
    private javax.swing.JButton jButtonCalcularFaltante;
    private javax.swing.JButton jButtonCalcularFaltante1;
    private javax.swing.JButton jButtonCalcularPagado;
    private javax.swing.JButton jButtonCalcularTotal;
    private javax.swing.JButton jButtonIngresar;
    private javax.swing.JLabel jLabelCodigo1;
    private javax.swing.JLabel jLabelCodigo2;
    private javax.swing.JLabel jLabelConcepto;
    private javax.swing.JLabel jLabelCuotas;
    private javax.swing.JLabel jLabelCuotas1;
    private javax.swing.JLabel jLabelCuotas2;
    private javax.swing.JLabel jLabelDetalles;
    private javax.swing.JLabel jLabelPagado;
    private javax.swing.JLabel jLabelSinPagar;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JLabel jLabelValor;
    private javax.swing.JLabel jLabelValorCuotas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelRegistro;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField textConcepto;
    private javax.swing.JTextArea textDetalles;
    private javax.swing.JTextField textIntereses;
    private javax.swing.JTextField textPagado;
    private javax.swing.JTextField textSinPagar;
    private javax.swing.JTextField textTotal;
    private javax.swing.JTextField textValorCuotas;
    // End of variables declaration//GEN-END:variables
}
