package Daniela.ComexApp.Frames;

import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Date;
import java.time.LocalDate;
import java.util.Calendar;
import service.OperacionNacionalParticipantesImpl;
import service.OperacionesNacionalesImpl;

/**
 *
 * @author Daniela
 */
public class IngresarNuevaOperacionNacional extends javax.swing.JFrame {

     String usuario = "", nombreCompleto = "";
    /**
     * Creates new form IngresarNuevosProductosAStock
     */
    public IngresarNuevaOperacionNacional() {
        initComponents();
        
        setSize(990, 460);
        setLayout(null);
        setLocationRelativeTo(null);
        setResizable(false);
        
        PaginaPrincipal paginaPrincipal = new PaginaPrincipal();
        
        usuario = paginaPrincipal.usuario;
        nombreCompleto = paginaPrincipal.nombreCompleto;
        
        setTitle("Ingresar nueva operación nacional - " + usuario + " - sistema ComexApp");
    }
    // icono
    public Image getLogo(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/loguito1.png"));
        return retValue;   
    }
    
    OperacionesNacionalesImpl ventaLocalService = new  OperacionesNacionalesImpl();

    public void LimpiarCampos(){
        textID.setText("");
        textCUIT.setText("");
        textEmpleado.setText("");
        textEmpresa.setText("");
        textMail.setText("");
        textNumero.setText("");
        textProductos.setText("");
        textCantidadProducto.setText("");
        textComprador.setText("");
        textPrecioTotal.setText("");
        textVendedor.setText("");
        cmbStatus1.setSelectedIndex(0);
        cmbTipoOperacion.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonIngresar = new javax.swing.JButton();
        jPanelRegistro = new javax.swing.JPanel();
        jLabelID = new javax.swing.JLabel();
        textID = new javax.swing.JTextField();
        jButtonInfo = new javax.swing.JButton();
        jLabelProductos = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textProductos = new javax.swing.JTextArea();
        jLabelCUIT = new javax.swing.JLabel();
        textCUIT = new javax.swing.JTextField();
        jLabelMail = new javax.swing.JLabel();
        textMail = new javax.swing.JTextField();
        jLabelEmpresa = new javax.swing.JLabel();
        textEmpresa = new javax.swing.JTextField();
        jLabelPrecio1 = new javax.swing.JLabel();
        textPrecioTotal = new javax.swing.JTextField();
        jLabelFechaRecibo = new javax.swing.JLabel();
        jLabelCantidad = new javax.swing.JLabel();
        textNumero = new javax.swing.JTextField();
        jLabelEmpleado = new javax.swing.JLabel();
        textEmpleado = new javax.swing.JTextField();
        jLabelStatus = new javax.swing.JLabel();
        cmbStatus1 = new javax.swing.JComboBox<>();
        jLabelCantidadProducto = new javax.swing.JLabel();
        jLabelComprador = new javax.swing.JLabel();
        textComprador = new javax.swing.JTextField();
        jLabelVendedor = new javax.swing.JLabel();
        textVendedor = new javax.swing.JTextField();
        textCantidadProducto = new javax.swing.JTextField();
        jLabelTipoOperacion = new javax.swing.JLabel();
        cmbTipoOperacion = new javax.swing.JComboBox<>();
        jDayChooser = new com.toedter.calendar.JDayChooser();
        jMonthChooser = new com.toedter.calendar.JMonthChooser();
        jYearChooser = new com.toedter.calendar.JYearChooser();
        jButtonAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getLogo());
        setIconImages(getIconImages());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonIngresar.setBackground(new java.awt.Color(0, 0, 153));
        jButtonIngresar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonIngresar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonIngresar.setText("Ingresar producto al sistema");
        jButtonIngresar.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jButtonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIngresarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, -1, -1));

        jPanelRegistro.setBackground(new java.awt.Color(204, 204, 204));
        jPanelRegistro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelID.setForeground(new java.awt.Color(0, 0, 153));
        jLabelID.setText("ID:");
        jPanelRegistro.add(jLabelID, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        textID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textID.setForeground(new java.awt.Color(0, 0, 153));
        textID.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelRegistro.add(textID, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 60, -1));

        jButtonInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/signo4.png"))); // NOI18N
        jButtonInfo.setBorder(null);
        jButtonInfo.setBorderPainted(false);
        jButtonInfo.setContentAreaFilled(false);
        jButtonInfo.setFocusPainted(false);
        jButtonInfo.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/signo5.png"))); // NOI18N
        jButtonInfo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/signo5.png"))); // NOI18N
        jButtonInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInfoActionPerformed(evt);
            }
        });
        jPanelRegistro.add(jButtonInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        jLabelProductos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelProductos.setForeground(new java.awt.Color(0, 0, 153));
        jLabelProductos.setText("Productos:");
        jPanelRegistro.add(jLabelProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setForeground(new java.awt.Color(0, 0, 153));

        textProductos.setColumns(10);
        textProductos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textProductos.setForeground(new java.awt.Color(0, 0, 153));
        textProductos.setLineWrap(true);
        textProductos.setRows(5);
        textProductos.setWrapStyleWord(true);
        jScrollPane2.setViewportView(textProductos);

        jPanelRegistro.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 150, 120));

        jLabelCUIT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelCUIT.setForeground(new java.awt.Color(0, 0, 153));
        jLabelCUIT.setText("CUIT:");
        jPanelRegistro.add(jLabelCUIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, -1, -1));

        textCUIT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textCUIT.setForeground(new java.awt.Color(0, 0, 153));
        textCUIT.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelRegistro.add(textCUIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 163, 30));

        jLabelMail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelMail.setForeground(new java.awt.Color(0, 0, 153));
        jLabelMail.setText("Mail:");
        jPanelRegistro.add(jLabelMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, -1, -1));

        textMail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textMail.setForeground(new java.awt.Color(0, 0, 153));
        textMail.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelRegistro.add(textMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 163, 30));

        jLabelEmpresa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelEmpresa.setForeground(new java.awt.Color(0, 0, 153));
        jLabelEmpresa.setText("Empresa:");
        jPanelRegistro.add(jLabelEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, -1, -1));

        textEmpresa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textEmpresa.setForeground(new java.awt.Color(0, 0, 153));
        textEmpresa.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelRegistro.add(textEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, 110, 30));

        jLabelPrecio1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelPrecio1.setForeground(new java.awt.Color(0, 0, 153));
        jLabelPrecio1.setText("Precio total:");
        jPanelRegistro.add(jLabelPrecio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, -1, -1));

        textPrecioTotal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textPrecioTotal.setForeground(new java.awt.Color(0, 0, 153));
        textPrecioTotal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelRegistro.add(textPrecioTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 110, 30));

        jLabelFechaRecibo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelFechaRecibo.setForeground(new java.awt.Color(0, 0, 153));
        jLabelFechaRecibo.setText("Fecha arribo:");
        jPanelRegistro.add(jLabelFechaRecibo, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, -1, -1));

        jLabelCantidad.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelCantidad.setForeground(new java.awt.Color(0, 0, 153));
        jLabelCantidad.setText("Número de contacto:");
        jPanelRegistro.add(jLabelCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 170, -1));

        textNumero.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textNumero.setForeground(new java.awt.Color(0, 0, 153));
        textNumero.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelRegistro.add(textNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 160, 30));

        jLabelEmpleado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelEmpleado.setForeground(new java.awt.Color(0, 0, 153));
        jLabelEmpleado.setText("Empleado:");
        jPanelRegistro.add(jLabelEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, -1, -1));

        textEmpleado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textEmpleado.setForeground(new java.awt.Color(0, 0, 153));
        textEmpleado.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelRegistro.add(textEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 160, 30));

        jLabelStatus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelStatus.setForeground(new java.awt.Color(0, 0, 153));
        jLabelStatus.setText("Status:");
        jPanelRegistro.add(jLabelStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 240, -1, -1));

        cmbStatus1.setForeground(new java.awt.Color(0, 0, 153));
        cmbStatus1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activa", "En transito", "Pendiente de cierre", "Completada", "Suspendida", "Inactiva" }));
        cmbStatus1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmbStatus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbStatus1ActionPerformed(evt);
            }
        });
        jPanelRegistro.add(cmbStatus1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 260, 120, 40));

        jLabelCantidadProducto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelCantidadProducto.setForeground(new java.awt.Color(0, 0, 153));
        jLabelCantidadProducto.setText("Cantidad producto:");
        jPanelRegistro.add(jLabelCantidadProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        jLabelComprador.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelComprador.setForeground(new java.awt.Color(0, 0, 153));
        jLabelComprador.setText("Comprador:");
        jPanelRegistro.add(jLabelComprador, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 100, -1));

        textComprador.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textComprador.setForeground(new java.awt.Color(0, 0, 153));
        textComprador.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelRegistro.add(textComprador, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 160, 30));

        jLabelVendedor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelVendedor.setForeground(new java.awt.Color(0, 0, 153));
        jLabelVendedor.setText("Vendedor:");
        jPanelRegistro.add(jLabelVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 100, 20));

        textVendedor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textVendedor.setForeground(new java.awt.Color(0, 0, 153));
        textVendedor.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelRegistro.add(textVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 160, 30));

        textCantidadProducto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textCantidadProducto.setForeground(new java.awt.Color(0, 0, 153));
        textCantidadProducto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelRegistro.add(textCantidadProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 150, 30));

        jLabelTipoOperacion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTipoOperacion.setForeground(new java.awt.Color(0, 0, 153));
        jLabelTipoOperacion.setText("Tipo de operación:");
        jPanelRegistro.add(jLabelTipoOperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 240, -1, -1));

        cmbTipoOperacion.setForeground(new java.awt.Color(0, 0, 153));
        cmbTipoOperacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Compra", "Venta" }));
        cmbTipoOperacion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmbTipoOperacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoOperacionActionPerformed(evt);
            }
        });
        jPanelRegistro.add(cmbTipoOperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 260, 150, 40));

        jDayChooser.setAlwaysFireDayProperty(true);
        jPanelRegistro.add(jDayChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 30, 360, 140));

        jMonthChooser.setDayChooser(jDayChooser);
        jMonthChooser.setYearChooser(jYearChooser);
        jPanelRegistro.add(jMonthChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 180, -1, -1));

        jYearChooser.setDayChooser(null);
        jPanelRegistro.add(jYearChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 180, -1, -1));

        jPanel1.add(jPanelRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 940, 330));

        jButtonAtras.setBackground(new java.awt.Color(0, 0, 153));
        jButtonAtras.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonAtras.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAtras.setText("Volver atrás");
        jButtonAtras.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jButtonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtrasActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 370, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 990, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIngresarActionPerformed

        String CUIT, empleado, empresa, mail, numeroContacto, productos,
            cantidadProductos, comprador, precioTotal, vendedor, 
                tipoOperacion = null, status = null, fechaRecibo;
                    
        int statusNivel = 0, ID, tipoOperacionNivel = 0;
        Date fechaRegistro, fechaArribo;
        int dia, mes, año;
        
        Boolean recepcionFuncion;
        
        ID = Integer.parseInt(textID.getText().trim());
        CUIT = textCUIT.getText().trim();
        empleado = textEmpleado.getText().trim();
        empresa = textEmpresa.getText().trim();
        mail = textMail.getText().trim();
        numeroContacto = textNumero.getText().trim();
        productos = textProductos.getText().trim();
        cantidadProductos = textCantidadProducto.getText().trim();
        comprador = textComprador.getText().trim();
        precioTotal = textPrecioTotal.getText().trim();
        vendedor = textVendedor.getText().trim();
        statusNivel = cmbStatus1.getSelectedIndex() + 1;
        tipoOperacionNivel = cmbTipoOperacion.getSelectedIndex() + 1;
        
        dia = jDayChooser.getDay();
        mes = jMonthChooser.getMonth() + 1;
        año = jYearChooser.getYear();
        
        fechaRecibo = año + "-" + mes + "-" + dia; 
        fechaArribo = Date.valueOf(fechaRecibo);
        fechaRegistro = Date.valueOf(LocalDate.now());

   
        if(statusNivel == 1){
           status = "Activa";
        } else if (statusNivel == 2){
           status = "En transito";
        } else if (statusNivel == 3){
           status = "Pendiente de cierre";
        } else if (statusNivel == 4){
           status = "Completada";
        } else if (statusNivel == 5){
           status = "Suspendida";
        } else if (statusNivel == 6){
           status = "Inactiva";
        }


        if(tipoOperacionNivel == 1){
           tipoOperacion = "Compra";
        } else if (statusNivel == 2){
           tipoOperacion = "Venta";
        } 
        
        recepcionFuncion = ventaLocalService.ingresoOperacionNacional(ID, CUIT, 
                empleado, empresa, mail, numeroContacto, productos, cantidadProductos, 
                comprador, precioTotal, vendedor, status, tipoOperacion, 
                fechaRegistro, fechaArribo);

        if(recepcionFuncion.equals(true)){
           OperacionNacionalParticipantesImpl opsNacPart = new OperacionNacionalParticipantesImpl();
           opsNacPart.ingresarConexionesOpNac(ID, comprador, vendedor, status);
           LimpiarCampos();
        }

    }//GEN-LAST:event_jButtonIngresarActionPerformed

    private void jButtonInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInfoActionPerformed

        InformacionIDOperacionNacional informacionIDOperacionNacional = new InformacionIDOperacionNacional();
        informacionIDOperacionNacional.setVisible(true);
        
    }//GEN-LAST:event_jButtonInfoActionPerformed

    private void jButtonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtrasActionPerformed
        
        Operaciones operaciones = new Operaciones();
        operaciones.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButtonAtrasActionPerformed

    private void cmbStatus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbStatus1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbStatus1ActionPerformed

    private void cmbTipoOperacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoOperacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTipoOperacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresarNuevaOperacionNacional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresarNuevaOperacionNacional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresarNuevaOperacionNacional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresarNuevaOperacionNacional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IngresarNuevaOperacionNacional().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbStatus1;
    private javax.swing.JComboBox<String> cmbTipoOperacion;
    private javax.swing.JButton jButtonAtras;
    private javax.swing.JButton jButtonInfo;
    private javax.swing.JButton jButtonIngresar;
    private com.toedter.calendar.JDayChooser jDayChooser;
    private javax.swing.JLabel jLabelCUIT;
    private javax.swing.JLabel jLabelCantidad;
    private javax.swing.JLabel jLabelCantidadProducto;
    private javax.swing.JLabel jLabelComprador;
    private javax.swing.JLabel jLabelEmpleado;
    private javax.swing.JLabel jLabelEmpresa;
    private javax.swing.JLabel jLabelFechaRecibo;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelMail;
    private javax.swing.JLabel jLabelPrecio1;
    private javax.swing.JLabel jLabelProductos;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JLabel jLabelTipoOperacion;
    private javax.swing.JLabel jLabelVendedor;
    private com.toedter.calendar.JMonthChooser jMonthChooser;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelRegistro;
    private javax.swing.JScrollPane jScrollPane2;
    private com.toedter.calendar.JYearChooser jYearChooser;
    private javax.swing.JTextField textCUIT;
    private javax.swing.JTextField textCantidadProducto;
    private javax.swing.JTextField textComprador;
    private javax.swing.JTextField textEmpleado;
    private javax.swing.JTextField textEmpresa;
    private javax.swing.JTextField textID;
    private javax.swing.JTextField textMail;
    private javax.swing.JTextField textNumero;
    private javax.swing.JTextField textPrecioTotal;
    private javax.swing.JTextArea textProductos;
    private javax.swing.JTextField textVendedor;
    // End of variables declaration//GEN-END:variables
}
