package Daniela.ComexApp.Frames;

import java.awt.Image;
import java.awt.Toolkit;
import service.StockImpl;

/**
 *
 * @author Daniela
 */
public class IngresarNuevosProductosAStock extends javax.swing.JFrame {

     String usuario = "", nombreCompleto = "";
    /**
     * Creates new form IngresarNuevosProductosAStock
     */
    public IngresarNuevosProductosAStock() {
        initComponents();
        
        setSize(650, 420);
        setLayout(null);
        setLocationRelativeTo(null);
        setResizable(false);
        
        PaginaPrincipal paginaPrincipal = new PaginaPrincipal();
        
        usuario = paginaPrincipal.usuario;
        nombreCompleto = paginaPrincipal.nombreCompleto;
        
        setTitle("Ingresar nuevos productos a stock - " + usuario + " - sistema ComexApp");
    }
    // icono
    public Image getLogo(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/loguito1.png"));
        return retValue;   
    }
    
    StockImpl stockService = new StockImpl();

    public void LimpiarCampos(){
        textID.setText("");
        textCodigo.setText("");
        textCuidados.setText("");
        textDetalle.setText("");
        textPaisOrigen.setText("");
        textPrecioUnitario.setText("");
        textTipoProducto.setText("");
        textProducto.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonIngresar = new javax.swing.JButton();
        jPanelRegistro = new javax.swing.JPanel();
        jLabelID = new javax.swing.JLabel();
        textID = new javax.swing.JTextField();
        jButtonInfo = new javax.swing.JButton();
        jLabelCodigo = new javax.swing.JLabel();
        textCodigo = new javax.swing.JTextField();
        jLabelDetalle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textDetalle = new javax.swing.JTextArea();
        jLabelCuidados = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textCuidados = new javax.swing.JTextArea();
        jLabelProducto = new javax.swing.JLabel();
        textProducto = new javax.swing.JTextField();
        jLabelTipo = new javax.swing.JLabel();
        textTipoProducto = new javax.swing.JTextField();
        jLabelPrecio = new javax.swing.JLabel();
        textPrecioUnitario = new javax.swing.JTextField();
        jLabelPaisOrigen = new javax.swing.JLabel();
        textPaisOrigen = new javax.swing.JTextField();
        jButtonAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getLogo());
        setIconImages(getIconImages());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonIngresar.setBackground(new java.awt.Color(0, 0, 153));
        jButtonIngresar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonIngresar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonIngresar.setText("Ingresar producto al sistema");
        jButtonIngresar.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jButtonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIngresarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, -1, -1));

        jPanelRegistro.setBackground(new java.awt.Color(204, 204, 204));
        jPanelRegistro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelID.setForeground(new java.awt.Color(0, 0, 153));
        jLabelID.setText("ID:");
        jPanelRegistro.add(jLabelID, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        textID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textID.setForeground(new java.awt.Color(0, 0, 153));
        textID.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelRegistro.add(textID, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 60, -1));

        jButtonInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/signo4.png"))); // NOI18N
        jButtonInfo.setBorder(null);
        jButtonInfo.setBorderPainted(false);
        jButtonInfo.setContentAreaFilled(false);
        jButtonInfo.setFocusPainted(false);
        jButtonInfo.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/signo5.png"))); // NOI18N
        jButtonInfo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/signo5.png"))); // NOI18N
        jButtonInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInfoActionPerformed(evt);
            }
        });
        jPanelRegistro.add(jButtonInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        jLabelCodigo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelCodigo.setForeground(new java.awt.Color(0, 0, 153));
        jLabelCodigo.setText("Código del producto;");
        jPanelRegistro.add(jLabelCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, -1, -1));

        textCodigo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textCodigo.setForeground(new java.awt.Color(0, 0, 153));
        textCodigo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelRegistro.add(textCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 163, -1));

        jLabelDetalle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelDetalle.setForeground(new java.awt.Color(0, 0, 153));
        jLabelDetalle.setText("Detalles:");
        jPanelRegistro.add(jLabelDetalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, -1, -1));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setForeground(new java.awt.Color(0, 0, 153));

        textDetalle.setColumns(10);
        textDetalle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textDetalle.setForeground(new java.awt.Color(0, 0, 153));
        textDetalle.setLineWrap(true);
        textDetalle.setRows(5);
        textDetalle.setWrapStyleWord(true);
        jScrollPane1.setViewportView(textDetalle);

        jPanelRegistro.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 180, 150));

        jLabelCuidados.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelCuidados.setForeground(new java.awt.Color(0, 0, 153));
        jLabelCuidados.setText("Cuidados requeridos:");
        jPanelRegistro.add(jLabelCuidados, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setForeground(new java.awt.Color(0, 0, 153));

        textCuidados.setColumns(10);
        textCuidados.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textCuidados.setForeground(new java.awt.Color(0, 0, 153));
        textCuidados.setLineWrap(true);
        textCuidados.setRows(5);
        textCuidados.setWrapStyleWord(true);
        jScrollPane2.setViewportView(textCuidados);

        jPanelRegistro.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 160, 150));

        jLabelProducto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelProducto.setForeground(new java.awt.Color(0, 0, 153));
        jLabelProducto.setText("Producto:");
        jPanelRegistro.add(jLabelProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, -1, -1));

        textProducto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textProducto.setForeground(new java.awt.Color(0, 0, 153));
        textProducto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelRegistro.add(textProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 163, 30));

        jLabelTipo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTipo.setForeground(new java.awt.Color(0, 0, 153));
        jLabelTipo.setText("Tipo de producto:");
        jPanelRegistro.add(jLabelTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, -1, -1));

        textTipoProducto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textTipoProducto.setForeground(new java.awt.Color(0, 0, 153));
        textTipoProducto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelRegistro.add(textTipoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 163, 30));

        jLabelPrecio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelPrecio.setForeground(new java.awt.Color(0, 0, 153));
        jLabelPrecio.setText("Precio unitario:");
        jPanelRegistro.add(jLabelPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, -1, -1));

        textPrecioUnitario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textPrecioUnitario.setForeground(new java.awt.Color(0, 0, 153));
        textPrecioUnitario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelRegistro.add(textPrecioUnitario, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 110, 30));

        jLabelPaisOrigen.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelPaisOrigen.setForeground(new java.awt.Color(0, 0, 153));
        jLabelPaisOrigen.setText("País de orígen:");
        jPanelRegistro.add(jLabelPaisOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, -1, -1));

        textPaisOrigen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textPaisOrigen.setForeground(new java.awt.Color(0, 0, 153));
        textPaisOrigen.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelRegistro.add(textPaisOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 110, 30));

        jPanel1.add(jPanelRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 570, 290));

        jButtonAtras.setBackground(new java.awt.Color(0, 0, 153));
        jButtonAtras.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonAtras.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAtras.setText("Volver atrás");
        jButtonAtras.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jButtonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtrasActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 340, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIngresarActionPerformed

        String codigo, cuidados, detalle, paisOrigen, precioUnitario, 
                tipoProducto, producto;
        int ID;
        
        Boolean recepcionFuncion;
          
        ID = Integer.parseInt(textID.getText().trim());
        codigo = textCodigo.getText().trim();
        cuidados = textCuidados.getText().trim();
        detalle = textDetalle.getText().trim();
        paisOrigen = textPaisOrigen.getText().trim();
        precioUnitario = textPrecioUnitario.getText().trim();
        tipoProducto = textTipoProducto.getText().trim();
        producto = textProducto.getText().trim();
        
        recepcionFuncion = stockService.ingresoNuevoProductoAStock(ID, codigo, 
                cuidados, detalle, paisOrigen, precioUnitario, tipoProducto, producto);

         if(recepcionFuncion.equals(true)){
           LimpiarCampos();
        }

    }//GEN-LAST:event_jButtonIngresarActionPerformed

    private void jButtonInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInfoActionPerformed

        InformacionIDProductos informacionIDProductos = new InformacionIDProductos();
        informacionIDProductos.setVisible(true);
        
    }//GEN-LAST:event_jButtonInfoActionPerformed

    private void jButtonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtrasActionPerformed
        
        StockProduccion stockProd = new StockProduccion();
        stockProd.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButtonAtrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresarNuevosProductosAStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresarNuevosProductosAStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresarNuevosProductosAStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresarNuevosProductosAStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IngresarNuevosProductosAStock().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtras;
    private javax.swing.JButton jButtonInfo;
    private javax.swing.JButton jButtonIngresar;
    private javax.swing.JLabel jLabelCodigo;
    private javax.swing.JLabel jLabelCuidados;
    private javax.swing.JLabel jLabelDetalle;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelPaisOrigen;
    private javax.swing.JLabel jLabelPrecio;
    private javax.swing.JLabel jLabelProducto;
    private javax.swing.JLabel jLabelTipo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelRegistro;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField textCodigo;
    private javax.swing.JTextArea textCuidados;
    private javax.swing.JTextArea textDetalle;
    private javax.swing.JTextField textID;
    private javax.swing.JTextField textPaisOrigen;
    private javax.swing.JTextField textPrecioUnitario;
    private javax.swing.JTextField textProducto;
    private javax.swing.JTextField textTipoProducto;
    // End of variables declaration//GEN-END:variables
}
