package Daniela.ComexApp.Frames;

import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Date;
import java.sql.Time;
import java.time.LocalDate;
import java.util.Calendar;
import org.jfree.data.time.Day;
import service.ReabastecimientoImpl;


/**
 *
 * @author Daniela
 */
public class IngresarNuevoReabastecimiento extends javax.swing.JFrame {

     String usuario = "", nombreCompleto = "";
    /**
     * Creates new form IngresarNuevosProductosAStock
     */
    public IngresarNuevoReabastecimiento() {
        initComponents();
        
        setSize(950, 420);
        setLayout(null);
        setLocationRelativeTo(null);
        setResizable(false);
        
        PaginaPrincipal paginaPrincipal = new PaginaPrincipal();
        
        usuario = paginaPrincipal.usuario;
        nombreCompleto = paginaPrincipal.nombreCompleto;
        
        setTitle("Ingresar nuevo reabastecimiento - " + usuario + " - sistema ComexApp");
    }
    // icono
    public Image getLogo(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/loguito1.png"));
        return retValue;   
    }
    
    ReabastecimientoImpl reabastecimientoService = new ReabastecimientoImpl();

    public void LimpiarCampos(){
        textID.setText("");
        textCuidados.setText("");
        textDetalle.setText("");
        textPaisOrigen.setText("");
        textPrecioUnitario.setText("");
        textPrecioTotal.setText("");
        textTipoProducto.setText("");
        textProducto.setText("");
        textCantidad.setText("");
        jDayChooser.setDay(0);
        jMonthChooser.setMonth(0);
        jYearChooser.setYear(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonIngresar = new javax.swing.JButton();
        jPanelRegistro = new javax.swing.JPanel();
        jLabelID = new javax.swing.JLabel();
        textID = new javax.swing.JTextField();
        jButtonInfo = new javax.swing.JButton();
        jLabelDetalle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textDetalle = new javax.swing.JTextArea();
        jLabelCuidados = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textCuidados = new javax.swing.JTextArea();
        jLabelProducto = new javax.swing.JLabel();
        textProducto = new javax.swing.JTextField();
        jLabelTipo = new javax.swing.JLabel();
        textTipoProducto = new javax.swing.JTextField();
        jLabelPrecio = new javax.swing.JLabel();
        textPrecioUnitario = new javax.swing.JTextField();
        jLabelPaisOrigen = new javax.swing.JLabel();
        textPaisOrigen = new javax.swing.JTextField();
        jLabelPrecio1 = new javax.swing.JLabel();
        textPrecioTotal = new javax.swing.JTextField();
        jLabelFechaRecibo = new javax.swing.JLabel();
        jLabelCantidad = new javax.swing.JLabel();
        textCantidad = new javax.swing.JTextField();
        jDayChooser = new com.toedter.calendar.JDayChooser();
        jMonthChooser = new com.toedter.calendar.JMonthChooser();
        jYearChooser = new com.toedter.calendar.JYearChooser();
        jButtonAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getLogo());
        setIconImages(getIconImages());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonIngresar.setBackground(new java.awt.Color(0, 0, 153));
        jButtonIngresar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonIngresar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonIngresar.setText("Ingresar producto al sistema");
        jButtonIngresar.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jButtonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIngresarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, -1, -1));

        jPanelRegistro.setBackground(new java.awt.Color(204, 204, 204));
        jPanelRegistro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelID.setForeground(new java.awt.Color(0, 0, 153));
        jLabelID.setText("ID:");
        jPanelRegistro.add(jLabelID, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        textID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textID.setForeground(new java.awt.Color(0, 0, 153));
        textID.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelRegistro.add(textID, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 60, -1));

        jButtonInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/signo4.png"))); // NOI18N
        jButtonInfo.setBorder(null);
        jButtonInfo.setBorderPainted(false);
        jButtonInfo.setContentAreaFilled(false);
        jButtonInfo.setFocusPainted(false);
        jButtonInfo.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/signo5.png"))); // NOI18N
        jButtonInfo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/signo5.png"))); // NOI18N
        jButtonInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInfoActionPerformed(evt);
            }
        });
        jPanelRegistro.add(jButtonInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        jLabelDetalle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelDetalle.setForeground(new java.awt.Color(0, 0, 153));
        jLabelDetalle.setText("Detalles:");
        jPanelRegistro.add(jLabelDetalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, -1, -1));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setForeground(new java.awt.Color(0, 0, 153));

        textDetalle.setColumns(10);
        textDetalle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textDetalle.setForeground(new java.awt.Color(0, 0, 153));
        textDetalle.setLineWrap(true);
        textDetalle.setRows(5);
        textDetalle.setWrapStyleWord(true);
        jScrollPane1.setViewportView(textDetalle);

        jPanelRegistro.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 120, 150));

        jLabelCuidados.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelCuidados.setForeground(new java.awt.Color(0, 0, 153));
        jLabelCuidados.setText("Cuidados requeridos:");
        jPanelRegistro.add(jLabelCuidados, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setForeground(new java.awt.Color(0, 0, 153));

        textCuidados.setColumns(10);
        textCuidados.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textCuidados.setForeground(new java.awt.Color(0, 0, 153));
        textCuidados.setLineWrap(true);
        textCuidados.setRows(5);
        textCuidados.setWrapStyleWord(true);
        jScrollPane2.setViewportView(textCuidados);

        jPanelRegistro.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 140, 90));

        jLabelProducto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelProducto.setForeground(new java.awt.Color(0, 0, 153));
        jLabelProducto.setText("Producto:");
        jPanelRegistro.add(jLabelProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, -1, -1));

        textProducto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textProducto.setForeground(new java.awt.Color(0, 0, 153));
        textProducto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelRegistro.add(textProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 163, 30));

        jLabelTipo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTipo.setForeground(new java.awt.Color(0, 0, 153));
        jLabelTipo.setText("Tipo de producto:");
        jPanelRegistro.add(jLabelTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, -1, -1));

        textTipoProducto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textTipoProducto.setForeground(new java.awt.Color(0, 0, 153));
        textTipoProducto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelRegistro.add(textTipoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 163, 30));

        jLabelPrecio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelPrecio.setForeground(new java.awt.Color(0, 0, 153));
        jLabelPrecio.setText("Precio unitario:");
        jPanelRegistro.add(jLabelPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, -1, -1));

        textPrecioUnitario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textPrecioUnitario.setForeground(new java.awt.Color(0, 0, 153));
        textPrecioUnitario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelRegistro.add(textPrecioUnitario, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 110, 30));

        jLabelPaisOrigen.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelPaisOrigen.setForeground(new java.awt.Color(0, 0, 153));
        jLabelPaisOrigen.setText("País de orígen:");
        jPanelRegistro.add(jLabelPaisOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, -1, -1));

        textPaisOrigen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textPaisOrigen.setForeground(new java.awt.Color(0, 0, 153));
        textPaisOrigen.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelRegistro.add(textPaisOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 120, 30));

        jLabelPrecio1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelPrecio1.setForeground(new java.awt.Color(0, 0, 153));
        jLabelPrecio1.setText("Precio total:");
        jPanelRegistro.add(jLabelPrecio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, -1, -1));

        textPrecioTotal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textPrecioTotal.setForeground(new java.awt.Color(0, 0, 153));
        textPrecioTotal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelRegistro.add(textPrecioTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 110, 30));

        jLabelFechaRecibo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelFechaRecibo.setForeground(new java.awt.Color(0, 0, 153));
        jLabelFechaRecibo.setText("Fecha recibo:");
        jPanelRegistro.add(jLabelFechaRecibo, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, -1, -1));

        jLabelCantidad.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelCantidad.setForeground(new java.awt.Color(0, 0, 153));
        jLabelCantidad.setText("Cantidad:");
        jPanelRegistro.add(jLabelCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 110, -1));

        textCantidad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textCantidad.setForeground(new java.awt.Color(0, 0, 153));
        textCantidad.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelRegistro.add(textCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 120, 30));
        jPanelRegistro.add(jDayChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, 360, 140));

        jMonthChooser.setDayChooser(jDayChooser);
        jMonthChooser.setYearChooser(jYearChooser);
        jPanelRegistro.add(jMonthChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 180, -1, -1));
        jPanelRegistro.add(jYearChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 210, -1, -1));

        jPanel1.add(jPanelRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 880, 290));

        jButtonAtras.setBackground(new java.awt.Color(0, 0, 153));
        jButtonAtras.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonAtras.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAtras.setText("Volver atrás");
        jButtonAtras.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jButtonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtrasActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 340, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 950, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIngresarActionPerformed

        String cuidados, detalle, paisOrigen, precioUnitario, precioTotal,
                tipoProducto, producto, cantidad, fechaRecibo;
        
        int ID, dia, mes, año;
        Date fechaLlegada, fechaRegistro;
        
        
        Boolean recepcionFuncion;
        
        ID = Integer.parseInt(textID.getText().trim());
        cuidados = textCuidados.getText().trim();
        detalle = textDetalle.getText().trim();
        paisOrigen = textPaisOrigen.getText().trim();
        precioUnitario = textPrecioUnitario.getText().trim();
        precioTotal = textPrecioTotal.getText().trim();
        cantidad = textCantidad.getText().trim();
        tipoProducto = textTipoProducto.getText().trim();
        producto = textProducto.getText().trim();
        
        dia = jDayChooser.getDay();
        mes = jMonthChooser.getMonth() + 1;
        año = jYearChooser.getYear();
        
        fechaRecibo = año + "-" + mes + "-" + dia; 
        fechaLlegada = Date.valueOf(fechaRecibo);
        fechaRegistro = Date.valueOf(LocalDate.now());
        
        recepcionFuncion = reabastecimientoService.ingresoSuministrosReabastecimiento
        (ID, cuidados, detalle, paisOrigen, precioUnitario, precioTotal, 
                cantidad, tipoProducto, producto, fechaRegistro, fechaLlegada);

         if(recepcionFuncion.equals(true)){
           LimpiarCampos();
        }

    }//GEN-LAST:event_jButtonIngresarActionPerformed

    private void jButtonInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInfoActionPerformed

        InformacionIDReabastecimiento informacionIDReabastecimiento = new InformacionIDReabastecimiento();
        informacionIDReabastecimiento.setVisible(true);
        
    }//GEN-LAST:event_jButtonInfoActionPerformed

    private void jButtonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtrasActionPerformed
        
        StockProduccion stockProd = new StockProduccion();
        stockProd.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButtonAtrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresarNuevoReabastecimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresarNuevoReabastecimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresarNuevoReabastecimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresarNuevoReabastecimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IngresarNuevoReabastecimiento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtras;
    private javax.swing.JButton jButtonInfo;
    private javax.swing.JButton jButtonIngresar;
    private com.toedter.calendar.JDayChooser jDayChooser;
    private javax.swing.JLabel jLabelCantidad;
    private javax.swing.JLabel jLabelCuidados;
    private javax.swing.JLabel jLabelDetalle;
    private javax.swing.JLabel jLabelFechaRecibo;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelPaisOrigen;
    private javax.swing.JLabel jLabelPrecio;
    private javax.swing.JLabel jLabelPrecio1;
    private javax.swing.JLabel jLabelProducto;
    private javax.swing.JLabel jLabelTipo;
    private com.toedter.calendar.JMonthChooser jMonthChooser;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelRegistro;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private com.toedter.calendar.JYearChooser jYearChooser;
    private javax.swing.JTextField textCantidad;
    private javax.swing.JTextArea textCuidados;
    private javax.swing.JTextArea textDetalle;
    private javax.swing.JTextField textID;
    private javax.swing.JTextField textPaisOrigen;
    private javax.swing.JTextField textPrecioTotal;
    private javax.swing.JTextField textPrecioUnitario;
    private javax.swing.JTextField textProducto;
    private javax.swing.JTextField textTipoProducto;
    // End of variables declaration//GEN-END:variables
}
