package Daniela.ComexApp.Frames;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;

import java.sql.SQLException;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


import java.awt.event.KeyEvent;
import service.Botones;
import service.InicioSesionService;

/**
 *
 * @author Daniela
 */
public class InicioSesion extends javax.swing.JFrame {

    
    /**
     * Creates new form InicioSesion
     */
    public InicioSesion() {
        initComponents();
        
        setSize(525, 650);
        setLayout(null);
        setLocationRelativeTo(null);
        setResizable(false);
        
        setTitle("Inicio de sesión - sistema ComexApp");
         
        // logo 
        ImageIcon logo  = new ImageIcon("src/imagenes/logo12.png");
        Icon iconoLogo = new ImageIcon(logo.getImage().getScaledInstance(jLabelLogo.getHeight(), 
                jLabelLogo.getWidth(), Image.SCALE_DEFAULT));
        jLabelLogo.setIcon(iconoLogo);
        this.repaint();
        
        jXBusyLabelCargaInicio.setVisible(false);
    }

    // icono
    public Image getLogo(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/loguito1.png"));
        return retValue;   
    }
    
    
    Botones botones = new Botones();
    
    
    public void ingresarAlSistemaBotonYMouse(){
        InicioSesionService inicioSesionService = new service.InicioSesionService();
        Boolean validez;
        
        validez = inicioSesionService.inicioDeSesion(textUsuario, textContraseña);
       
            if(validez.equals(true)){
                jXBusyLabelCargaInicio.setVisible(true);
                JOptionPane.showMessageDialog(null, "Ingresando al sistema");
                
                LimpiarCamposCorrectos();
                PaginaPrincipal principal = new PaginaPrincipal();
                principal.setVisible(true);
                this.dispose();
                
            }else if (validez.equals(false)){
                LimpiarCamposErroneos();
                if(textUsuario.equals("") && textContraseña.equals("")){
                    JOptionPane.showMessageDialog(null, "Los campos estan vacios");
                } else if (!textUsuario.equals("") && !textContraseña.equals("")){
                JOptionPane.showMessageDialog(null, "Usuario y contraseña no "
                        + "encontrados en la base. \n\n " + "Por favor, vuelva "
                        + "a intentarlo");
                }  
            }
    }
    
    public void LimpiarCamposCorrectos(){
          textUsuario.setText("");
          textContraseña.setText("");
    }
    
    public void LimpiarCamposErroneos(){
        textUsuario.setBackground(Color.red);
        textContraseña.setBackground(Color.red);
        textUsuario.setText("");
        textContraseña.setText("");
        textUsuario.setBackground(Color.white);
        textContraseña.setBackground(Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBlanco = new javax.swing.JPanel();
        jLabelLogo1 = new javax.swing.JLabel();
        jLabelLogo = new javax.swing.JLabel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelSub = new javax.swing.JLabel();
        jLabelInicio = new javax.swing.JLabel();
        jPanelAzul = new javax.swing.JPanel();
        jLabelUsuario = new javax.swing.JLabel();
        textUsuario = new javax.swing.JTextField();
        jLabelContraseña = new javax.swing.JLabel();
        textContraseña = new javax.swing.JPasswordField();
        jButtonIngresar = new javax.swing.JButton();
        jLabelMensaje = new javax.swing.JLabel();
        jButtonCrearCuenta = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jXBusyLabelCargaInicio = new org.jdesktop.swingx.JXBusyLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getLogo());
        setIconImages(getIconImages());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelBlanco.setBackground(new java.awt.Color(255, 255, 255));
        jPanelBlanco.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelLogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo12.png"))); // NOI18N
        jPanelBlanco.add(jLabelLogo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 150, 120));
        jPanelBlanco.add(jLabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 150, 120));

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(0, 0, 153));
        jLabelTitulo.setText("ComexApp");
        jPanelBlanco.add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 242, 103));

        jLabelSub.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jLabelSub.setForeground(new java.awt.Color(0, 0, 153));
        jLabelSub.setText("¡Bienvenido al sistema!");
        jPanelBlanco.add(jLabelSub, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 330, 103));

        jLabelInicio.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jLabelInicio.setForeground(new java.awt.Color(0, 0, 153));
        jLabelInicio.setText("Inicio de sesión");
        jPanelBlanco.add(jLabelInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 220, 103));

        getContentPane().add(jPanelBlanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 310));

        jPanelAzul.setBackground(new java.awt.Color(0, 0, 153));
        jPanelAzul.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelUsuario.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabelUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUsuario.setText("Usuario:");
        jPanelAzul.add(jLabelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 170, 40));

        textUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textUsuario.setForeground(new java.awt.Color(0, 0, 153));
        jPanelAzul.add(textUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 260, 40));

        jLabelContraseña.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabelContraseña.setForeground(new java.awt.Color(255, 255, 255));
        jLabelContraseña.setText("Contraseña:");
        jPanelAzul.add(jLabelContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 170, 40));

        textContraseña.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textContraseña.setForeground(new java.awt.Color(0, 0, 153));
        textContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textContraseñaActionPerformed(evt);
            }
        });
        textContraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textContraseñaKeyPressed(evt);
            }
        });
        jPanelAzul.add(textContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 260, 40));

        jButtonIngresar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonIngresar.setForeground(new java.awt.Color(0, 0, 153));
        jButtonIngresar.setText("Ingresar");
        jButtonIngresar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 153), new java.awt.Color(0, 0, 153), new java.awt.Color(0, 0, 153), new java.awt.Color(0, 0, 153)));
        jButtonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIngresarActionPerformed(evt);
            }
        });
        jPanelAzul.add(jButtonIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 140, 50));

        jLabelMensaje.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelMensaje.setForeground(new java.awt.Color(255, 0, 51));
        jPanelAzul.add(jLabelMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, -1, -1));

        jButtonCrearCuenta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonCrearCuenta.setForeground(new java.awt.Color(0, 0, 153));
        jButtonCrearCuenta.setText("Crear cuenta");
        jButtonCrearCuenta.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 153), new java.awt.Color(0, 0, 153), new java.awt.Color(0, 0, 153), new java.awt.Color(0, 0, 153)));
        jButtonCrearCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearCuentaActionPerformed(evt);
            }
        });
        jPanelAzul.add(jButtonCrearCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 140, 30));

        jButtonSalir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonSalir.setForeground(new java.awt.Color(0, 0, 153));
        jButtonSalir.setText("Salir");
        jButtonSalir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 153), new java.awt.Color(0, 0, 153), new java.awt.Color(0, 0, 153), new java.awt.Color(0, 0, 153)));
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        jPanelAzul.add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, 140, 25));

        jXBusyLabelCargaInicio.setForeground(new java.awt.Color(0, 153, 0));
        jXBusyLabelCargaInicio.setText("Ingresando al sistema");
        jXBusyLabelCargaInicio.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanelAzul.add(jXBusyLabelCargaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 200, -1));

        getContentPane().add(jPanelAzul, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 313, 550, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIngresarActionPerformed
        
       ingresarAlSistemaBotonYMouse();
       
    }//GEN-LAST:event_jButtonIngresarActionPerformed

    private void jButtonCrearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearCuentaActionPerformed
     
        RegistroUsuarios registrarUsuarios = new RegistroUsuarios();
        registrarUsuarios.setVisible(true);
        
    }//GEN-LAST:event_jButtonCrearCuentaActionPerformed

    private void textContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textContraseñaActionPerformed

    }//GEN-LAST:event_textContraseñaActionPerformed

    private void textContraseñaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textContraseñaKeyPressed
      
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
         ingresarAlSistemaBotonYMouse();
        }
        
    }//GEN-LAST:event_textContraseñaKeyPressed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        
        botones.botonSalirSistema();
        
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
       
        botones.botonSalirSistema();
        
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCrearCuenta;
    private javax.swing.JButton jButtonIngresar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabelContraseña;
    private javax.swing.JLabel jLabelInicio;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelLogo1;
    private javax.swing.JLabel jLabelMensaje;
    private javax.swing.JLabel jLabelSub;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPanel jPanelAzul;
    private javax.swing.JPanel jPanelBlanco;
    private org.jdesktop.swingx.JXBusyLabel jXBusyLabelCargaInicio;
    private javax.swing.JPasswordField textContraseña;
    private javax.swing.JTextField textUsuario;
    // End of variables declaration//GEN-END:variables


}
