package Daniela.ComexApp.Frames;

import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Date;
import java.sql.Time;
import java.time.LocalDate;
import java.util.Calendar;
import javax.swing.JOptionPane;
import org.jfree.data.time.Day;
import service.ReabastecimientoService;
import service.StockImpl;



/**
 *
 * @author Daniela
 */
public class ModificarFechaStockYSumi extends javax.swing.JFrame {

     String usuario = "", nombreCompleto = "";
     Date fechaStock, fechaSuministro;
     
     
    /**
     * Creates new form ModificarFechaStockYSumi
     */
    public ModificarFechaStockYSumi() {
        initComponents();
        
        setSize(600, 420);
        setLayout(null);
        setLocationRelativeTo(null);
        setResizable(false);
        
        PaginaPrincipal paginaPrincipal = new PaginaPrincipal();
        GestionSuministros gestionSuministros = new GestionSuministros();
        
        usuario = paginaPrincipal.usuario;
        nombreCompleto = paginaPrincipal.nombreCompleto;
        
        
        setTitle("Modificación de fecha de ingreso - " + usuario + " - sistema ComexApp");
    }
    // icono
    public Image getLogo(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/loguito1.png"));
        return retValue;   
    }
    
    ReabastecimientoService reabastecimientoService = new ReabastecimientoService();

    public void LimpiarCampos(){
        textProducto.setText("");
        jDayChooser.setDay(0);
        jMonthChooser.setMonth(0);
        jYearChooser.setYear(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelRegistro = new javax.swing.JPanel();
        jLabelProducto = new javax.swing.JLabel();
        textProducto = new javax.swing.JTextField();
        jLabelFechaRecibo = new javax.swing.JLabel();
        jDayChooser = new com.toedter.calendar.JDayChooser();
        jMonthChooser = new com.toedter.calendar.JMonthChooser();
        jYearChooser = new com.toedter.calendar.JYearChooser();
        jLabelID = new javax.swing.JLabel();
        textID = new javax.swing.JTextField();
        jButtonModificarIngresoSuministros = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(getLogo());
        setIconImages(getIconImages());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelRegistro.setBackground(new java.awt.Color(204, 204, 204));
        jPanelRegistro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelProducto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelProducto.setForeground(new java.awt.Color(0, 0, 153));
        jLabelProducto.setText("Producto:");
        jPanelRegistro.add(jLabelProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        textProducto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textProducto.setForeground(new java.awt.Color(0, 0, 153));
        textProducto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelRegistro.add(textProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 163, 30));

        jLabelFechaRecibo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelFechaRecibo.setForeground(new java.awt.Color(0, 0, 153));
        jLabelFechaRecibo.setText("Fecha de ingreso:");
        jPanelRegistro.add(jLabelFechaRecibo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));
        jPanelRegistro.add(jDayChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 360, 140));

        jMonthChooser.setDayChooser(jDayChooser);
        jMonthChooser.setYearChooser(jYearChooser);
        jPanelRegistro.add(jMonthChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, -1, -1));
        jPanelRegistro.add(jYearChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, -1, -1));

        jLabelID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelID.setForeground(new java.awt.Color(0, 0, 153));
        jLabelID.setText("ID:");
        jPanelRegistro.add(jLabelID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        textID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textID.setForeground(new java.awt.Color(0, 0, 153));
        textID.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelRegistro.add(textID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 70, 30));

        jPanel1.add(jPanelRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 710, 290));

        jButtonModificarIngresoSuministros.setBackground(new java.awt.Color(0, 0, 153));
        jButtonModificarIngresoSuministros.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonModificarIngresoSuministros.setForeground(new java.awt.Color(255, 255, 255));
        jButtonModificarIngresoSuministros.setText("Modificar fecha de ingreso de suministros");
        jButtonModificarIngresoSuministros.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jButtonModificarIngresoSuministros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarIngresoSuministrosActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonModificarIngresoSuministros, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 335, -1, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonModificarIngresoSuministrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarIngresoSuministrosActionPerformed

        String producto, fechaRecibo;
        int ID, dia, mes, año;
        Date fechaLlegada;
        
        producto = textProducto.getText().trim();
        ID = Integer.parseInt(textID.getText().trim());
        
        dia = jDayChooser.getDay();
        mes = jMonthChooser.getMonth() + 1;
        año = jYearChooser.getYear();
        
        fechaRecibo = año + "-" + mes + "-" + dia; 
        fechaLlegada = Date.valueOf(fechaRecibo);
        
        reabastecimientoService.modificarFechaIngreso(ID, producto, fechaLlegada);
        
    }//GEN-LAST:event_jButtonModificarIngresoSuministrosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarFechaStockYSumi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarFechaStockYSumi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarFechaStockYSumi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarFechaStockYSumi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarFechaStockYSumi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonModificarIngresoSuministros;
    private com.toedter.calendar.JDayChooser jDayChooser;
    private javax.swing.JLabel jLabelFechaRecibo;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelProducto;
    private com.toedter.calendar.JMonthChooser jMonthChooser;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelRegistro;
    private com.toedter.calendar.JYearChooser jYearChooser;
    private javax.swing.JTextField textID;
    private javax.swing.JTextField textProducto;
    // End of variables declaration//GEN-END:variables
}
