package Daniela.ComexApp.Frames;

import java.awt.Image;
import java.awt.Toolkit;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import service.PreguntasSeguridadImpl;

/**
 *
 * @author Daniela
 */
public class TengoUsuario extends javax.swing.JFrame {
 
    public String usuario = "";
    /**
     * Creates new form TengoUsuario
     *  PARA RECUPERAR CONTRASEÑA A PARTIR DE UN USUARIO Y PREGUNTAS DE SEGURIDAD
     */
    public TengoUsuario() {
        initComponents();
        
        setSize(600, 510);
        setLayout(null);
        setLocationRelativeTo(null);
        setResizable(false);
        
        usuario = textUsuario.getText().trim();

        setTitle("Recupero contraseña - sistema ComexApp");
    }
    
    // icono
    public Image getLogo(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/loguito1.png"));
        return retValue;   
    }
    
    PreguntasSeguridadImpl preguntasSeguridadService = new PreguntasSeguridadImpl();

    
    public int numeroDePreguntaUnoADevolver(String eleccionUno){
        
        int eleccionUnoNivel = 0;
        
        if(eleccionUno.equals("¿Cúal es el nombre de tu primera mascota?")){
           eleccionUnoNivel = 0;
        } else if (eleccionUno.equals("¿En que ciudad naciste?")){
           eleccionUnoNivel = 1;
        } else if (eleccionUno.equals("¿Nombre de tus abuelos?")){
           eleccionUnoNivel = 2;
        } else if (eleccionUno.equals("¿En que año terminaste el secundario?")){
           eleccionUnoNivel = 3;
        } else if (eleccionUno.equals("¿Cúal es el nombre de tu primer amor?")){
           eleccionUnoNivel = 4;
        } else if (eleccionUno.equals("¿En que empresa tuviste tu primer empleo?")){
           eleccionUnoNivel = 5;
        } else if (eleccionUno.equals("¿Cúal fue tu primer show en vivo?")){
           eleccionUnoNivel = 6;
        }
        
        return eleccionUnoNivel;
    }
    
    public int numeroDePreguntaDosADevolver(String eleccionDos){
        
        int eleccionDosNivel = 0;
        
        if(eleccionDos.equals("¿Cúal es el nombre de tu mascota?")){
           eleccionDosNivel = 0;
        } else if (eleccionDos.equals("¿En que ciudad vives?")){
           eleccionDosNivel = 1;
        } else if (eleccionDos.equals("¿Nombre de tu videojuego favorito?")){
           eleccionDosNivel = 2;
        } else if (eleccionDos.equals("¿Nombre de tu serie favorita?")){
           eleccionDosNivel = 3;
        } else if (eleccionDos.equals("¿Cúal es tu hobbie favorito?")){
           eleccionDosNivel = 4;
        } else if (eleccionDos.equals("¿Cúal es el nombre de tu banda/artista favorito?")){
           eleccionDosNivel = 5;
        } else if (eleccionDos.equals("¿Qué deporte practicas?")){
           eleccionDosNivel = 6;
        }
        return eleccionDosNivel;
    }
    
    public int numeroDePreguntaTresADevolver(String eleccionTres){
        
        int eleccionTresNivel = 0;

        if(eleccionTres.equals("¿Qué mascota te gustaría tener?")){
           eleccionTresNivel = 0;
        } else if (eleccionTres.equals("¿En que ciudad te gustaría vivir?")){
           eleccionTresNivel = 1;
        } else if (eleccionTres.equals("¿Cúal es tu sueño principal?")){
           eleccionTresNivel = 2;
        } else if (eleccionTres.equals("¿Qué otra carrera o estudios estudiarías?")){
           eleccionTresNivel = 3;
        } else if (eleccionTres.equals("¿Cúal es el nombre de tu pareja?")){
           eleccionTresNivel = 4;
        } else if (eleccionTres.equals("¿Que banda/artista te gustaría ver en vivo?")){
           eleccionTresNivel = 5;
        }
        return eleccionTresNivel;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelPreg1 = new javax.swing.JLabel();
        cmbPreguntaUno = new javax.swing.JComboBox<>();
        textPreguntaUno = new javax.swing.JTextField();
        jLabelPreg2 = new javax.swing.JLabel();
        jButtonConfirmar1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        cmbPreguntaDos = new javax.swing.JComboBox<>();
        textPreguntaDos = new javax.swing.JTextField();
        jLabelPreg3 = new javax.swing.JLabel();
        cmbPreguntaTres = new javax.swing.JComboBox<>();
        textPreguntaTres = new javax.swing.JTextField();
        jButtonConfirmar = new javax.swing.JButton();
        textUsuario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButtonBuscar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        textNombre = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getLogo());
        setIconImages(getIconImages());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(0, 0, 153));
        jLabelTitulo.setText("Preguntas de seguridad");
        jPanel1.add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 330, 50));

        jLabelPreg1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabelPreg1.setForeground(new java.awt.Color(0, 0, 153));
        jLabelPreg1.setText("Pregunta de seguridad N°1:");
        jPanel1.add(jLabelPreg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 200, 40));

        cmbPreguntaUno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbPreguntaUno.setForeground(new java.awt.Color(0, 0, 153));
        cmbPreguntaUno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "¿Cúal es el nombre de tu primera mascota?", "¿En que ciudad naciste?", "¿Nombre de tus abuelos?", "¿En que año terminaste el secundario?", "¿Cúal es el nombre de tu primer amor?", "¿En que empresa tuviste tu primer empleo?", "¿Cúal fue tu primer show en vivo?" }));
        jPanel1.add(cmbPreguntaUno, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 95, 380, 30));

        textPreguntaUno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textPreguntaUno.setForeground(new java.awt.Color(0, 0, 153));
        jPanel1.add(textPreguntaUno, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 250, 30));

        jLabelPreg2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabelPreg2.setForeground(new java.awt.Color(0, 0, 153));
        jLabelPreg2.setText("Pregunta de seguridad N°2:");
        jPanel1.add(jLabelPreg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 200, 30));

        jButtonConfirmar1.setBackground(new java.awt.Color(0, 0, 153));
        jButtonConfirmar1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButtonConfirmar1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonConfirmar1.setText("Volver");
        jButtonConfirmar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmar1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonConfirmar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 80, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 230));

        jPanel2.setBackground(new java.awt.Color(0, 0, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbPreguntaDos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbPreguntaDos.setForeground(new java.awt.Color(0, 0, 153));
        cmbPreguntaDos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "¿Cúal es el nombre de tu mascota?", "¿En que ciudad vives?", "¿Nombre de tu videojuego favorito?", "¿Nombre de tu serie favorita?", "¿Cúal es tu hobbie favorito?", "¿Cúal es el nombre de tu banda/artista favorito?", "¿Qué deporte practicas?", " " }));
        jPanel2.add(cmbPreguntaDos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, -10, 380, 30));

        textPreguntaDos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textPreguntaDos.setForeground(new java.awt.Color(0, 0, 153));
        jPanel2.add(textPreguntaDos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 250, 30));

        jLabelPreg3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabelPreg3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPreg3.setText("Pregunta de seguridad N°3:");
        jPanel2.add(jLabelPreg3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 200, 30));

        cmbPreguntaTres.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbPreguntaTres.setForeground(new java.awt.Color(0, 0, 153));
        cmbPreguntaTres.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "¿Qué mascota te gustaría tener?", "¿En que ciudad te gustaría vivir?", "¿Cúal es tu sueño principal?", "¿Qué otra carrera o estudios estudiarías?", "¿Cúal es el nombre de tu pareja?", "¿Que banda/artista te gustaría ver en vivo?" }));
        jPanel2.add(cmbPreguntaTres, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 380, 30));

        textPreguntaTres.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textPreguntaTres.setForeground(new java.awt.Color(0, 0, 153));
        jPanel2.add(textPreguntaTres, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 250, 30));

        jButtonConfirmar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButtonConfirmar.setForeground(new java.awt.Color(0, 0, 153));
        jButtonConfirmar.setText("Confirmar ");
        jButtonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 170, 30));
        jPanel2.add(textUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, 110, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Usuario:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, -1, -1));

        jButtonBuscar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButtonBuscar.setForeground(new java.awt.Color(0, 0, 153));
        jButtonBuscar.setText("Buscar preguntas");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 170, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, -1, -1));
        jPanel2.add(textNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, 110, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 610, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarActionPerformed
        
        String preguntaUno, preguntaDos, preguntaTres, preguntaUnoC, preguntaDosC, 
                preguntaTresC, usuario;
        
        Boolean coincidenConInfoAlmacenada;
       
        usuario = textUsuario.getText().trim();
        
        preguntaUno = textPreguntaUno.getText().trim();
        preguntaDos = textPreguntaDos.getText().trim();
        preguntaTres = textPreguntaTres.getText().trim();
          
        preguntaUnoC = preguntasSeguridadService.recuperoEleccionUno(usuario);
        preguntaDosC = preguntasSeguridadService.recuperoEleccionDos(usuario);
        preguntaTresC = preguntasSeguridadService.recuperoEleccionTres(usuario);
        
        
        if(preguntaUno.equals(preguntaUnoC) && preguntaDos.equals(preguntaDosC) 
                && preguntaTresC.equals(preguntaTresC)){

            String contraseña = preguntasSeguridadService.recuperarContraseña(usuario);
            JOptionPane.showMessageDialog(null, usuario + " tu contraseña es " + contraseña);
        } else{
            String mensaje = "No podemos recuperar tu contraseña. "
                    + "\n\n Los datos ingresados no coinciden con los del sistema.";
            JOptionPane.showMessageDialog(null, mensaje, "Recupero de contraseña "
                    + "sin éxito", 0);
        }

        
    }//GEN-LAST:event_jButtonConfirmarActionPerformed

    private void jButtonConfirmar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmar1ActionPerformed
        
        InicioSesion inicioSesion = new InicioSesion();
        inicioSesion.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButtonConfirmar1ActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed

        String usuario = textUsuario.getText().trim();
        String nombre = textNombre.getText().trim();
        
        String preguntaUno = preguntasSeguridadService.recuperarPreguntaUno(usuario, nombre);
        String preguntaDos = preguntasSeguridadService.recuperarPreguntaDos(usuario, nombre);
        String preguntaTres = preguntasSeguridadService.recuperarPreguntaTres(usuario, nombre);
        
        int eleccionUno = numeroDePreguntaUnoADevolver(preguntaUno);
        int eleccionDos = numeroDePreguntaDosADevolver(preguntaDos);
        int eleccionTres = numeroDePreguntaTresADevolver(preguntaTres);
        
        cmbPreguntaUno.setSelectedIndex(eleccionUno);
        cmbPreguntaDos.setSelectedIndex(eleccionDos);
        cmbPreguntaTres.setSelectedIndex(eleccionTres);
        
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TengoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TengoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TengoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TengoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TengoUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbPreguntaDos;
    private javax.swing.JComboBox<String> cmbPreguntaTres;
    private javax.swing.JComboBox<String> cmbPreguntaUno;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonConfirmar;
    private javax.swing.JButton jButtonConfirmar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelPreg1;
    private javax.swing.JLabel jLabelPreg2;
    private javax.swing.JLabel jLabelPreg3;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField textNombre;
    private javax.swing.JTextField textPreguntaDos;
    private javax.swing.JTextField textPreguntaTres;
    private javax.swing.JTextField textPreguntaUno;
    private javax.swing.JTextField textUsuario;
    // End of variables declaration//GEN-END:variables
}
